# Default LID metrics settings.
recipe_dir: .
exp_tag: null
exp_dir: ${recipe_dir}/exp/${exp_tag}
metrics:
  - metric:
      _target_: espnet3.systems.esp2_lid.metrics.accuracy.Accuracy
      ref_key: ref
      hyp_key: hyp
  - metric:
      _target_: espnet3.systems.esp2_lid.metrics.classification_report.ClassificationReport
