#!/usr/bin/env python3

"""Prepare segments file (+ phoneme text)."""

# Copyright 2020 Tomoki Hayashi
#  Apache 2.0  (http://www.apache.org/licenses/LICENSE-2.0)

import argparse
import logging
import os
import shutil
import sys

from distutils.util import strtobool


def load_lab(lab_path):
    """Load the force alignment labels."""
    with open(lab_path, "r") as f:
        lines = [line.replace("\n", "") for line in f.readlines()]
    start_times_in_sec = [float(line.split("\t")[0]) for line in lines]
    end_times_in_sec = [float(line.split("\t")[1]) for line in lines]
    phonemes = [line.split("\t")[2] for line in lines]
    return start_times_in_sec, end_times_in_sec, phonemes


def main():
    """Run main process."""
    parser = argparse.ArgumentParser(
        description="Prepare segments from the force alignment files",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--replace_text_with_phoneme",
        default=False,
        type=strtobool,
        help="whether to replace kaldi text file with phoneme "
        "generated by the force alignment results",
    )
    parser.add_argument("wav_scp", type=str, help="wav scp file")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG,
        stream=sys.stdout,
        format="%(asctime)s (%(module)s:%(lineno)d) %(levelname)s: %(message)s",
    )

    segments_path = os.path.dirname(args.wav_scp) + "/segments"
    segments_writer = open(segments_path, "w")
    if args.replace_text_with_phoneme:
        text_path = os.path.dirname(args.wav_scp) + "/text"
        if os.path.exists(text_path):
            shutil.copy2(text_path, text_path + ".bak")
        text_writer = open(text_path, "w")

    with open(args.wav_scp) as f:
        for line in f:
            recording_id, path = line.split()
            lab_path = path.replace(".wav", ".lab")
            if not os.path.exists(lab_path):
                logging.warning(f"{lab_path} does not exists. skipped it.")
                continue
            labels = load_lab(lab_path)
            if labels[2][0] in ["sil"]:
                segment_begin = "{:.3f}".format(labels[0][1])
                start_idx = 1
            else:
                segment_begin = "{:.3f}".format(labels[0][0])
                start_idx = 0
            assert len(labels[2][-1]) == 0
            if labels[2][-2] in ["sp"]:
                segment_end = "{:.3f}".format(labels[0][-2])
                end_idx = -2
            else:
                segment_end = "{:.3f}".format(labels[1][-1])
                end_idx = -1

            # As we assume that there's only a single utterance per recording,
            # utt_id is same as recording_id.
            # https://kaldi-asr.org/doc/data_prep.html
            utt_id = recording_id
            segments_writer.write(
                "{} {} {} {}\n".format(utt_id, recording_id, segment_begin, segment_end)
            )
            if args.replace_text_with_phoneme:
                text_writer.write(
                    "{} {}\n".format(utt_id, " ".join(labels[2][start_idx:end_idx]))
                )

    segments_writer.close()
    if args.replace_text_with_phoneme:
        text_writer.close()


if __name__ == "__main__":
    main()
