# Inference/decoding configuration template for ESPnet3 ASR.
# Keep only inference-relevant knobs.
exp_dir: ${load_yaml:conf/training.yaml,exp_dir}
inference_dir: ${exp_dir}/inference
dataset_dir: ${load_yaml:conf/training.yaml,dataset_dir}

dataset:
  _target_: espnet3.components.data.data_organizer.DataOrganizer
  test:

parallel:
  env: local
  n_workers: 1

model:

input_key: speech
output_fn: src.inference.build_output

provider:
  _target_: espnet3.systems.base.inference_provider.InferenceProvider
runner:
  _target_: espnet3.systems.base.inference_runner.InferenceRunner
