"""TTS system implementation

This module adds new stages on top of the base system, including
computing x-vectors, removing long-short utterances, creating token lists,
and supporting VITS training with GAN-based adversarial learning.
"""

import logging
import time
from collections import Counter
from pathlib import Path
from typing import Any, Dict

import lightning as L
import soundfile as sf
import torch
from hydra.utils import instantiate
from omegaconf import DictConfig, OmegaConf
from src.gan_trainer import build_gan_trainer
from src.xvector_provider import XVectorProvider
from src.xvector_runner import XVectorRunner

from espnet2.text.build_tokenizer import build_tokenizer
from espnet2.text.cleaner import TextCleaner
from espnet2.train.abs_gan_espnet_model import AbsGANESPnetModel
from espnet3.components.modeling.lightning_module import ESPnetLightningModule
from espnet3.components.trainers.trainer import ESPnet3LightningTrainer
from espnet3.parallel.parallel import set_parallel
from espnet3.systems.base.system import BaseSystem
from espnet3.utils.task_utils import get_espnet_model, save_espnet_config

logger = logging.getLogger(__name__)


def _instantiate_model(config: DictConfig) -> Any:
    task = config.get("task")
    if task:
        model_config = OmegaConf.to_container(config.model, resolve=True)
        model = get_espnet_model(task, model_config)
        _patch_collect_feats(model)
        return model
    return instantiate(config.model)


def _patch_collect_feats(model: Any) -> None:
    """
    espnet3's collect_stats only iterates the dict returned by ``collect_feats``,
    so input-tensor shape, such as ``speech_shape``, ``text_shape``, are 
    missing. This patch passes the raw inputs through, matching what espnet2's
    main_funcs/collect_stats.py writes from the batch dict.
    """
    if not isinstance(model, AbsGANESPnetModel):
        return
    original = model.collect_feats

    def collect_feats_with_inputs(**kwargs):
        out = original(**kwargs)
        if "speech" in kwargs and "speech_lengths" in kwargs:
            out["speech"] = kwargs["speech"]
            out["speech_lengths"] = kwargs["speech_lengths"]
        if "text" in kwargs and "text_lengths" in kwargs:
            out["text"] = kwargs["text"]
            out["text_lengths"] = kwargs["text_lengths"]
        return out

    model.collect_feats = collect_feats_with_inputs


class TTSSystem(BaseSystem):
    """TTS-specific system.

    This system adds:
      - x-vector computation
      - Removing long-short utterances
      - Creating token lists

    Additional stage log paths:
        | Stage                 | Path reference                  |
        |---                   |---                              |
        | compute_xvectors     | training_config.xvector.save_path |
        | remove_long_short    | training_config.remove_long_short.save_path |
        | create_token_list    | training_config.token_list.save_path |
    """

    def __init__(
        self,
        training_config=None,
        inference_config=None,
        metrics_config=None,
        **kwargs,
    ) -> None:
        """Initialize the TTS system with TTS-specific stage mappings."""
        super().__init__(
            training_config=training_config,
            inference_config=inference_config,
            metrics_config=metrics_config,
            stage_log_mapping={
                "compute_xvectors": "training_config.xvector.save_path",
                "remove_long_short": "training_config.remove_long_short.save_path",
                "create_token_list": "training_config.token_list.save_path",
            },
            **kwargs,
        )

    def compute_xvectors(self, *args, **kwargs):
        """Compute x-vectors for multiple data splits using parallel execution.

        X-vectors (speaker embeddings) are extracted using a pre-trained model
        for train, valid, and test splits. They can be used as speaker conditioning
        in TTS models.

        This method uses espnet3 manifest files generated by the dataset builder.
        Manifest format: utt_id\twav_path\ttext\tspeaker_id (TSV)

        Configuration should include:
            training_config.xvector.pretrained_model: Model tag or path
            training_config.xvector.toolkit: 'espnet', 'speechbrain', or 'rawnet'
            training_config.xvector.save_path: Output directory
            training_config.xvector.splits: List of splits to process (train, valid, test)
            training_config.xvector.batch_size: Batch size for processing
            training_config.xvector.device: Device to use (default: cuda:0 if available)

        Raises:
            RuntimeError: If required configuration is missing or manifest files not found.
        """
        self._reject_stage_args("compute_xvectors", args, kwargs)
        logger.info("TTSSystem.compute_xvectors(): starting x-vector computation")

        # Parse the parallel configuration early to set up parallelism for the x-vector runner
        if self.training_config.get("parallel"):
            set_parallel(self.training_config.parallel)

        xvec_cfg = self.training_config.get("xvector", None)
        if xvec_cfg is None:
            raise RuntimeError(
                "training_config.xvector must be set for compute_xvectors stage."
            )
        save_path_str = xvec_cfg.get("save_path", None)
        if save_path_str is None:
            raise RuntimeError(
                "training_config.xvector.save_path must be set for compute_xvectors stage."
            )
        save_path = Path(save_path_str)
        save_path.mkdir(parents=True, exist_ok=True)

        # Get list of splits to process (Default: all splits)
        splits = xvec_cfg.get("splits", ["train", "valid", "test"])

        if isinstance(splits, str):
            splits = [splits]

        manifest_paths = xvec_cfg.get("manifest_paths", {})

        logger.info(f"Will process splits: {splits}")
        logger.info(f"Manifest paths: {manifest_paths}")

        # Validate toolkit and model
        toolkit = xvec_cfg.get("toolkit", "speechbrain")
        pretrained_model = xvec_cfg.get(
            "pretrained_model", "speechbrain/spkrec-ecapa-voxceleb"
        )
        device = xvec_cfg.get(
            "device", "cuda:0" if torch.cuda.is_available() else "cpu"
        )

        # Process each split
        for split in splits:
            logger.info(f"Processing split: {split}")

            manifest_path = manifest_paths.get(split, None)
            if manifest_path is None:
                manifest_path = f"data/manifest/{split}.tsv"
            manifest_path = Path(manifest_path).resolve()
            if not manifest_path.exists():
                raise RuntimeError(
                    f"Manifest file not found for split '{split}': {manifest_path}. Please generate the manifest file using the create_dataset stage and ensure the path is correct."
                )

            utterances, _ = XVectorProvider._load_manifest(manifest_path)
            n_utts = len(utterances)
            if n_utts == 0:
                raise RuntimeError(f"No utterances found in manifest: {manifest_path}.")

            logger.info(f"Split '{split}': {n_utts} utterances in {manifest_path}")

            batch_size = xvec_cfg.get("batch_size", None)
            async_mode = xvec_cfg.get("async_mode", False)
            spk_embed_tag = xvec_cfg.get("spk_embed_tag", "spk_embed")
            output_subdir = save_path / f"{spk_embed_tag}_{split}"

            provider = XVectorProvider(
                config=self.training_config,
                params={
                    "toolkit": toolkit,
                    "pretrained_model": pretrained_model,
                    "device": device,
                    "manifest_path": str(manifest_path),
                    "output_dir": str(output_subdir),
                },
            )

            runner = XVectorRunner(
                provider=provider,
                batch_size=batch_size,
                async_mode=async_mode,
            )

            logger.info(
                f"Processing {n_utts} utterances for x-vector extraction (split: {split})"
            )

            indices = list(range(n_utts))
            results = runner(indices)

            if results is None:
                logger.info(
                    f"Async job submitted for split '{split}'. Check result directory for outputs."
                )
                continue

            flat = []
            for item in results:
                if isinstance(item, list):
                    flat.extend(item)
                else:
                    flat.append(item)
            n_ok = sum(1 for r in flat if r.get("status") == "ok")
            n_skipped = sum(1 for r in flat if r.get("status") == "skipped")
            logger.info(
                f"X-vectors for split '{split}' saved to {output_subdir} "
                f"({n_ok} new, {n_skipped} skipped)"
            )

        logger.info("X-vector computation completed for all splits")

    def remove_long_short(self, *args, **kwargs):
        """Remove long-short utterances based on duration thresholds.

        This stage processes manifest files to filter out utterances that are too short or too long based on specified duration thresholds. It uses librosa to check audio durations and saves filtered manifests for downstream stages.

        Configuration should include:
            training_config.remove_long_short.min_wav_duration: Minimum duration in seconds
            training_config.remove_long_short.max_wav_duration: Maximum duration in seconds
            training_config.remove_long_short.save_path: Directory to save filtered manifests
            training_config.remove_long_short.splits: List of splits to process (train, valid, test)
            training_config.remove_long_short.manifest_paths: Optional dict of split to manifest path (default: data/manifest/{split}.tsv)

        Raises:
            RuntimeError: If required configuration is missing or manifest files not found.
        """
        self._reject_stage_args("remove_long_short", args, kwargs)
        logger.info(
            "TTSSystem.remove_long_short(): starting long-short utterance removal"
        )

        rls_cfg = self.training_config.get("remove_long_short", None)
        if rls_cfg is None:
            raise RuntimeError(
                "training_config.remove_long_short must be set for remove_long_short stage."
            )
        save_path_str = rls_cfg.get("save_path", None)
        if save_path_str is None:
            raise RuntimeError(
                "training_config.remove_long_short.save_path must be set for remove_long_short stage."
            )
        save_path = Path(save_path_str)

        min_duration = rls_cfg.get("min_wav_duration", None)
        max_duration = rls_cfg.get("max_wav_duration", None)
        if min_duration is None or max_duration is None:
            raise RuntimeError(
                "training_config.remove_long_short.min_wav_duration and "
                "max_wav_duration must be set for remove_long_short stage."
            )

        # Get list of splits to process (Default: all splits)
        splits = rls_cfg.get("splits", ["train", "valid", "test"])

        if isinstance(splits, str):
            splits = [splits]

        manifest_paths = rls_cfg.get("manifest_paths", {})

        save_path.mkdir(parents=True, exist_ok=True)
        logger.info(
            f"Removing long-short utterances with "
            f"min_duration={min_duration}s, max_duration={max_duration}s"
        )

        for split in splits:
            logger.info(f"Processing split: {split}")

            manifest_path = manifest_paths.get(split) if manifest_paths else None
            if manifest_path is None:
                manifest_path = f"data/manifest/{split}.tsv"
            manifest_path = Path(manifest_path).resolve()
            filtered_manifest_path = save_path / manifest_path.name
            if not manifest_path.exists():
                raise RuntimeError(
                    f"Manifest file not found for split '{split}': {manifest_path}. Please generate the manifest file using the create_dataset stage and ensure the path is correct."
                )

            n_kept = 0
            n_dropped_duration = 0
            n_dropped_empty = 0
            filtered_entries = []

            with open(manifest_path, "r", encoding="utf-8") as f:
                for line in f:
                    parts = line.rstrip("\n").split("\t")

                    # Mirror espnet2's `NF != 1` filter: drop rows without text.
                    if len(parts) < 3 or parts[2].strip() == "":
                        n_dropped_empty += 1
                        continue

                    wav_path = parts[1]
                    duration = sf.info(wav_path).duration

                    # Strict inequalities to match espnet2 tts.sh awk filter.
                    if duration <= min_duration or duration >= max_duration:
                        n_dropped_duration += 1
                        continue

                    filtered_entries.append(
                        line if line.endswith("\n") else line + "\n"
                    )
                    n_kept += 1

            with open(filtered_manifest_path, "w", encoding="utf-8") as f:
                f.writelines(filtered_entries)

            logger.info(
                f"Split '{split}': kept {n_kept}, dropped {n_dropped_duration} "
                f"by duration, dropped {n_dropped_empty} by empty text → "
                f"{filtered_manifest_path}"
            )

        logger.info(
            f"Long-short utterance removal completed. Filtered manifests saved to: {save_path}"
        )

    def create_token_list(self, *args, **kwargs):
        """Create token list from training data.

        This stage processes the training manifest to extract unique tokens from the text transcriptions and saves them to a token list file.

        Configuration should include:
            training_config.token_list.save_path: Path to save the token list file
            training_config.token_list.manifest_path: Path to the training manifest file (default: data/manifest/train.tsv)

        Raises:
            RuntimeError: If required configuration is missing or manifest file not found.
        """
        self._reject_stage_args("create_token_list", args, kwargs)
        logger.info("TTSSystem.create_token_list(): starting token list creation")

        tl_cfg = self.training_config.get("token_list", None)
        if tl_cfg is None:
            raise RuntimeError(
                "training_config.token_list must be set for create_token_list stage."
            )
        save_path_str = tl_cfg.get("save_path", None)
        if save_path_str is None:
            raise RuntimeError(
                "training_config.token_list.save_path must be set for create_token_list stage."
            )
        filename = tl_cfg.get("filename", None)
        if filename is None:
            raise RuntimeError(
                "training_config.token_list.filename must be set "
                "(e.g. 'tokens.txt'); save_path is the output directory."
            )
        save_dir = Path(save_path_str)
        save_dir.mkdir(parents=True, exist_ok=True)
        output_file = save_dir / filename

        manifest_path = Path(
            tl_cfg.get("manifest_path", "data/manifest/train.tsv")
        ).resolve()

        if not manifest_path.exists():
            raise RuntimeError(
                f"Manifest file not found for token list creation: {manifest_path}. Please ensure the manifest file is generated and the path is correct."
            )

        # Declare text processing parameters with defaults (matching espnet2 defaults where applicable)
        cleaner = tl_cfg.get("cleaner", None)
        token_type = tl_cfg.get("token_type", "char")
        bpemodel = tl_cfg.get("bpemodel", None)
        delimiter = tl_cfg.get("delimiter", None)
        space_symbol = tl_cfg.get("space_symbol", "<space>")
        non_linguistic_symbols = tl_cfg.get("non_linguistic_symbols", None)
        remove_non_linguistic_symbols = tl_cfg.get(
            "remove_non_linguistic_symbols", False
        )
        g2p = tl_cfg.get("g2p", None)
        add_symbol = tl_cfg.get("add_symbol", [])
        add_nonsplit_symbol = tl_cfg.get("add_nonsplit_symbol", [])
        cutoff = tl_cfg.get("cutoff", 0)
        vocabulary_size = tl_cfg.get("vocabulary_size", 0)

        cleaner: TextCleaner = TextCleaner(cleaner)
        tokenizer = build_tokenizer(
            token_type=token_type,
            bpemodel=bpemodel,
            delimiter=delimiter,
            space_symbol=space_symbol,
            non_linguistic_symbols=non_linguistic_symbols,
            remove_non_linguistic_symbols=remove_non_linguistic_symbols,
            g2p_type=g2p,
            nonsplit_symbol=add_nonsplit_symbol,
        )

        counter = Counter()

        with open(manifest_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.rstrip()
                parts = line.split("\t")
                text = parts[2]
                cleaned_text = cleaner(text)
                tokens = tokenizer.text2tokens(cleaned_text)
                for t in tokens:
                    counter[t] += 1

        # Sort by the number of occurrences in descending order
        # and filter lower frequency words than cutoff value
        words_and_counts = list(
            filter(
                lambda x: x[1] > cutoff, sorted(counter.items(), key=lambda x: -x[1])
            )
        )

        # Restrict the vocabulary size
        if vocabulary_size > 0:
            if vocabulary_size < len(add_symbol):
                raise RuntimeError(f"vocabulary_size is too small: {vocabulary_size}")
            words_and_counts = words_and_counts[: vocabulary_size - len(add_symbol)]

        # Parse the values of --add_symbol and --add_nonsplit_symbol
        for symbol_and_id in add_symbol + add_nonsplit_symbol:
            # e.g symbol="<blank>:0"
            try:
                symbol, idx = symbol_and_id.split(":")
                idx = int(idx)
            except ValueError:
                raise RuntimeError(f"Format error: e.g. '<blank>:0': {symbol_and_id}")
            symbol = symbol.strip()

            # e.g. idx=0  -> append as the first symbol
            # e.g. idx=-1 -> append as the last symbol
            if idx < 0:
                idx = len(words_and_counts) + 1 + idx
            words_and_counts.insert(idx, (symbol, None))

        # Write words
        with open(output_file, "w", encoding="utf-8") as f:
            for word, count in words_and_counts:
                f.write(f"{word}\n")

        # Logging
        total_count = sum(counter.values())
        invocab_count = sum(c for w, c in words_and_counts if c is not None)
        if total_count > 0:
            logger.info(
                f"OOV rate = {(total_count - invocab_count) / total_count * 100:.2f} %"
            )
        else:
            logger.warning("create_token_list: manifest contained no tokens.")

    def _ensure_directories(self) -> None:
        config = self.training_config
        Path(config.exp_dir).mkdir(parents=True, exist_ok=True)
        if hasattr(config, "stats_dir"):
            Path(config.stats_dir).mkdir(parents=True, exist_ok=True)

    def _build_trainer(self) -> ESPnet3LightningTrainer:
        config = self.training_config
        model = _instantiate_model(config)
        if isinstance(model, AbsGANESPnetModel):
            return build_gan_trainer(config, model)

        lit_model = ESPnetLightningModule(model, config)
        return ESPnet3LightningTrainer(
            model=lit_model,
            exp_dir=config.exp_dir,
            config=config.trainer,
            best_model_criterion=config.best_model_criterion,
        )

    def _prepare_training_runtime(self) -> None:
        config = self.training_config
        self._ensure_directories()

        if config.get("parallel"):
            set_parallel(config.parallel)

        if config.get("seed") is not None:
            L.seed_everything(int(config.seed), workers=True)

        torch.set_float32_matmul_precision("high")

    def collect_stats(self, *args, **kwargs):
        """Run the collect_stats stage using the configured trainer.

        Prepares the training runtime (directories, parallelism, seed), then
        delegates to the trainer's ``collect_stats`` method.  Positional and
        keyword stage arguments are rejected to avoid silent misconfiguration.

        Args:
            *args: Must be empty.  Passing any positional argument raises
                ``ValueError`` via ``_reject_stage_args``.
            **kwargs: Must be empty.  Passing any keyword argument raises
                ``ValueError`` via ``_reject_stage_args``.

        Returns:
            None

        Raises:
            ValueError: If any positional or keyword arguments are passed.

        Notes:
            The ``normalize: null`` pattern from recipe configs is intentionally
            preserved — no normalization is applied during stats collection.

        Examples:
            >>> from omegaconf import OmegaConf
            >>> cfg = OmegaConf.create({"exp_dir": "/tmp/exp"})
            >>> system = TTSSystem(training_config=cfg)
            >>> system.collect_stats()  # runs stats collection end-to-end
        """
        self._reject_stage_args("collect_stats", args, kwargs)
        start = time.perf_counter()
        self._prepare_training_runtime()

        # Preserve `normalize: null` from recipe configs.
        trainer = self._build_trainer()
        trainer.collect_stats()
        logger.info(
            "Collect stats finished in %.2fs | exp_dir=%s stats_dir=%s",
            time.perf_counter() - start,
            self.training_config.exp_dir,
            getattr(self.training_config, "stats_dir", None),
        )

    def train(self, *args, **kwargs):
        """Run the training stage using the configured trainer.

        Prepares the runtime, optionally saves the ESPnet config, then calls
        ``trainer.fit`` with any keyword arguments drawn from
        ``training_config.fit``.  For GAN models, a ``GANTTSLightningTrainer``
        is used automatically; for all other models, ``ESPnet3LightningTrainer``
        is used.

        Args:
            *args: Must be empty.  Passing any positional argument raises
                ``ValueError`` via ``_reject_stage_args``.
            **kwargs: Must be empty.  Passing any keyword argument raises
                ``ValueError`` via ``_reject_stage_args``.

        Returns:
            None

        Raises:
            ValueError: If any positional or keyword arguments are passed.

        Notes:
            ``training_config.fit`` is forwarded verbatim to ``trainer.fit``.
            Common keys include ``max_epochs``, ``ckpt_path``, etc.

        Examples:
            >>> from omegaconf import OmegaConf
            >>> cfg = OmegaConf.create({
            ...     "exp_dir": "/tmp/exp",
            ...     "task": "tts",
            ...     "model": {"_target_": "my.Model"},
            ...     "fit": {"max_epochs": 10},
            ... })
            >>> system = TTSSystem(training_config=cfg)
            >>> system.train()  # trains the model for 10 epochs
        """
        self._reject_stage_args("train", args, kwargs)
        start = time.perf_counter()
        self._prepare_training_runtime()

        task = self.training_config.get("task")
        if task:
            save_espnet_config(task, self.training_config, self.training_config.exp_dir)

        trainer = self._build_trainer()

        fit_kwargs: Dict[str, Any] = {}
        if hasattr(self.training_config, "fit") and self.training_config.fit:
            fit_kwargs = OmegaConf.to_container(self.training_config.fit, resolve=True)

        trainer.fit(**fit_kwargs)
        logger.info(
            "Training finished in %.2fs | exp_dir=%s model=%s",
            time.perf_counter() - start,
            self.training_config.exp_dir,
            (
                self.training_config.model.get("_target_", None)
                if isinstance(self.training_config.model, DictConfig)
                else None
            ),
        )
