""" TTS system implementation

This module adds new stages on top of the base system, including 
computing x-vectors, removing long-short utterances, creating token lists,
and supporting VITS training with GAN-based adversarial learning.
"""

import logging
import subprocess
from pathlib import Path

from omegaconf import DictConfig
from espnet3.systems.base.system import BaseSystem
from xvector_provider import XVectorProvider
from xvector_runner import XVectorRunner

logger = logging.getLogger(__name__)

class TTSSystem(BaseSystem):
    """TTS-specific system.

    This system adds:
      - x-vector computation
      - Removing long-short utterances
      - Creating token lists
      - VITS training with GAN-based adversarial learning

    The system automatically detects VITS models and applies appropriate
    training strategies including:
      - Multi-optimizer training (generator + discriminator)
      - Generator-only statistics collection
      - Configurable training strategy (generator_first, skip_discriminator_prob)

    Additional stage log paths:
        | Stage                 | Path reference                  |
        |---                   |---                              |
        | compute_xvectors     | training_config.xvector.save_path |
        | remove_long_short    | training_config.remove_long_short.save_path |
        | create_token_list    | training_config.token_list.save_path |
    """

    def __init__(
        self,
        training_config=None,
        inference_config=None,
        metrics_config=None,
        **kwargs,
    ) -> None:
        """Initialize the TTS system with TTS-specific stage mappings."""
        super().__init__(
            training_config=training_config,
            inference_config=inference_config,
            metrics_config=metrics_config,
            stage_log_mapping={
                "compute_xvectors": "training_config.xvector.save_path",
                "remove_long_short": "training_config.remove_long_short.save_path",
                "create_token_list": "training_config.token_list.save_path",
            },
            **kwargs,
        )
    
    def compute_xvectors(self, *args, **kwargs):
        """Compute x-vectors for multiple data splits using parallel execution.
        
        X-vectors (speaker embeddings) are extracted using a pre-trained model
        for train, valid, and test splits. They can be used as speaker conditioning
        in TTS models.
        
        This method uses espnet3 manifest files generated by the dataset builder.
        Manifest format: utt_id\twav_path\ttext\tspeaker_id (TSV)
        
        Configuration should include:
            training_config.xvector.pretrained_model: Model tag or path
            training_config.xvector.toolkit: 'espnet', 'speechbrain', or 'rawnet'
            training_config.xvector.save_path: Output directory
            training_config.xvector.splits: List of splits to process (train, valid, test)
            training_config.xvector.batch_size: Batch size for processing (optional)
            training_config.xvector.device: Device to use (default: cuda:0 if available)

        Raises:
            RuntimeError: If required configuration is missing or manifest files not found.
        """
        self._reject_stage_args("compute_xvectors", args, kwargs)
        logger.info("TTSSystem.compute_xvectors(): starting x-vector computation")
        
        xvec_cfg = self.training_config.get("xvector", None)
        save_path = Path(xvec_cfg.get("save_path", None)) if xvec_cfg else None

        if xvec_cfg is None or save_path is None:
            raise RuntimeError("training_config.xvector and training_config.xvector.save_path must be set for compute_xvectors stage.")

        save_path.mkdir(parents=True, exist_ok=True)
        
        # Get list of splits to process
        splits = xvec_cfg.get("splits", None)

        if splits is None:
            raise RuntimeError("training_config.xvector.splits must be set to specify which data splits to process (e.g., ['train', 'valid', 'test'])")

        if isinstance(splits, str):
            splits = [splits]
        
        # Get manifest directory (configurable, default: data/manifest)
        manifest_dir = Path(xvec_cfg.get("manifest_dir", "data/manifest"))
        
        logger.info(f"Will process splits: {splits}")
        logger.info(f"Manifest directory: {manifest_dir}")
        
        # Validate toolkit and model
        toolkit = xvec_cfg.get("toolkit", None)
        pretrained_model = xvec_cfg.get("pretrained_model", None)
        device = xvec_cfg.get("device", "cuda:0" if self._has_cuda() else "cpu")

        if toolkit is None or pretrained_model is None:
            raise RuntimeError("training_config.xvector.toolkit and training_config.xvector.pretrained_model must be set for compute_xvectors stage.")
        
        # Process each split
        for split in splits:
            logger.info(f"Processing split: {split}")
            
            # Get manifest file path for this split
            manifest_path = manifest_dir / f"{split}.tsv"
            if not manifest_path.exists():
                logger.warning(f"Manifest file not found for split '{split}': {manifest_path}. Skipping.")
                continue
            
            # Read manifest file to extract audio paths and speaker information
            utterances = []
            speaker_to_utterances = {}
            
            with open(manifest_path, "r", encoding="utf-8") as f:
                for line in f:
                    parts = line.strip().split("\t")
                    
                    utt_id = parts[0]
                    wav_path = Path(parts[1])
                    speaker_id = parts[3]
                    
                    utterances.append((utt_id, wav_path))
                    
                    if speaker_id not in speaker_to_utterances:
                        speaker_to_utterances[speaker_id] = []
                    speaker_to_utterances[speaker_id].append(utt_id)
            
            if not utterances:
                raise RuntimeError(f"No utterances found in manifest: {manifest_path}.")
            
            logger.info(f"Split '{split}': Loaded {len(utterances)} utterances from {len(speaker_to_utterances)} speakers")
            
            # Build provider with manifest data
            provider = XVectorProvider(
                config=self.training_config,
                params={
                    "toolkit": toolkit,
                    "pretrained_model": pretrained_model,
                    "device": device,
                    "utterances": utterances,
                    "speaker_to_utterances": speaker_to_utterances,
                }
            )
            
            # Build runner with split-specific output tag
            batch_size = xvec_cfg.get("batch_size", None)
            async_mode = xvec_cfg.get("async_mode", False)
            spk_embed_tag = xvec_cfg.get("spk_embed_tag", "spk_embed")
            
            runner = XVectorRunner(
                provider=provider,
                output_dir=str(save_path),
                spk_embed_tag=spk_embed_tag,
                batch_size=batch_size,
                async_mode=async_mode,
            )
            
            logger.info(f"Processing {len(utterances)} utterances for x-vector extraction (split: {split})")
            
            # Run extraction
            indices = list(range(len(utterances)))
            results = runner(indices)
            
            # Write results with split suffix
            if results is not None:
                runner.write_results(results, suffix=f"_{split}")
                logger.info(f"X-vectors for split '{split}' saved to {save_path}")
            else:
                logger.info(f"Async job submitted for split '{split}'. Check result directory for outputs.")
        
        logger.info("X-vector computation completed for all splits")
    
    def remove_long_short(self, *args, **kwargs):
        """Remove long-short utterances based on duration thresholds.
        
        This stage processes manifest files to filter out utterances that are too short or too long based on specified duration thresholds. It uses librosa to check audio durations and saves filtered manifests for downstream stages.

        Configuration should include:
            training_config.remove_long_short.min_wav_duration: Minimum duration in seconds
            training_config.remove_long_short.max_wav_duration: Maximum duration in seconds
            training_config.remove_long_short.sampling_rate: Sampling rate for duration calculation
            training_config.remove_long_short.save_path: Directory to save filtered manifests
            training_config.remove_long_short.splits: List of splits to process (train, valid, test)
            training_config.remove_long_short.manifest_paths: Optional dict of split to manifest path (default: data/manifest/{split}.tsv)
        
        Raises:
            RuntimeError: If required configuration is missing or manifest files not found.
        """
        self._reject_stage_args("remove_long_short", args, kwargs)
        logger.info("TTSSystem.remove_long_short(): starting long-short utterance removal")

        rls_cfg = self.training_config.get("remove_long_short", None)
        save_path = Path(rls_cfg.get("save_path", None)) if rls_cfg else None

        if rls_cfg is None or save_path is None:
            raise RuntimeError("training_config.remove_long_short and training_config.remove_long_short.save_path must be set for remove_long_short stage.")
        
        min_duration = rls_cfg.get("min_wav_duration", None)
        max_duration = rls_cfg.get("max_wav_duration", None)
        sampling_rate = rls_cfg.get("sampling_rate", None)

        if min_duration is None or max_duration is None or sampling_rate is None:
            raise RuntimeError("training_config.remove_long_short.min_wav_duration, max_wav_duration, and sampling_rate must be set for remove_long_short stage.")

        # Get list of splits to process
        splits = rls_cfg.get("splits", None)

        if splits is None:
            raise RuntimeError("training_config.remove_long_short.splits must be set to specify which data splits to process (e.g., ['train', 'valid', 'test'])")

        if isinstance(splits, str):
            splits = [splits]
        
        # Get manifest directory (configurable, default: data/manifest)
        manifest_paths = rls_cfg.get("manifest_paths", {})

        save_path.mkdir(parents=True, exist_ok=True)
        logger.info(f"Removing long-short utterances with min_duration={min_duration}s, max_duration={max_duration}s, sampling_rate={sampling_rate}Hz")

        for split in splits:
            logger.info(f"Processing split: {split}")
            
            # Get manifest file path for this split
            manifest_path = Path(manifest_paths.get(split, None)).resolve() if manifest_paths else Path(f"data/manifest/{split}.tsv")
            filtered_manifest_path = save_path / manifest_path.name
            if not manifest_path.exists():
                raise RuntimeError(f"Manifest file not found for split '{split}': {manifest_path}. Please ensure the manifest file is generated and the path is correct.")
            
            # Read manifest file to extract audio paths and speaker information
            filtered_entries = []
            
            with open(manifest_path, "r", encoding="utf-8") as f:
                for line in f:
                    parts = line.strip().split("\t")
                    
                    wav_path = Path(parts[1])
                    length = librosa.get_duration(filename=str(wav_path), sr=sampling_rate)

                    if length < min_duration or length > max_duration:
                        continue

                    filtered_entries.append(line)
            
            with open(filtered_manifest_path, "w", encoding="utf-8") as f:
                f.write("\n".join(filtered_entries))

        logger.info(f"Long-short utterance removal completed. Filtered manifests saved to: {save_path}")
