queue_rules:
  - name: default
    conditions:
      # This is the default queue, which will be used for all PRs that do not match any other queue.
      # While the PR is in the queue, Mergify will wait for the following CIs to complete successfully before merging it into master.
      - "check-success~=check_kaldi_symlinks"
      - "check-success~=check_installable_on_"
      - "check-success~=unit_test_espnet2_and_integration_test_espnet2"
      - "check-success~=test_import"
      - "check-success~=unit_test_espnet2_and_espnet3_on_debian12"
      - "check-success~=test_configuration_espnet2"
      - "check-success~=test_integration_espnet2"
      - "check-success~=test_integration_espnet3"
      - "check-success~=test_python_espnet2"
      - "check-success~=test_python_espnet3"
      - "check-success~=test_shell_espnet2"
      - "check-success~=test_utils_espnet2"

pull_request_rules:
  - name: automatic merge if label=auto-merge
    conditions:
      - "label=auto-merge"
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default # <--  This is the name of the queue defined above
  - name: "add label=auto-merge for PR by mergify"
    conditions:
      - author=mergify[bot]
    actions:
      label:
        add: ["auto-merge"]
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflict :(
      label:
        add: ["conflicts"]
  - name: unlabel conflicts
    conditions:
      - -conflict
    actions:
      label:
        remove: ["conflicts"]
  - name: "auto add label=ESPnet2"
    conditions:
      - files~=^(espnet2/|egs2/)
    actions:
      label:
        add: ["ESPnet2"]
  - name: "auto add label=ASR"
    conditions:
      - files~=^(espnet*/asr|egs*/*/asr1)
    actions:
      label:
        add: ["ASR"]
  - name: "auto add label=TTS"
    conditions:
      - files~=^(espnet*/tts|egs*/*/tts1)
    actions:
      label:
        add: ["TTS"]
  - name: "auto add label=MT"
    conditions:
      - files~=^(espnet*/mt|egs*/*/mt1)
    actions:
      label:
        add: ["MT"]
  - name: "auto add label=LM"
    conditions:
      - files~=^(espnet*/lm)
    actions:
      label:
        add: ["LM"]
  - name: "auto add label=README"
    conditions:
      - files~=README.md
    actions:
      label:
        add: ["README"]
  - name: "auto add label=Documentation"
    conditions:
      - files~=^doc/
    actions:
      label:
        add: ["Documentation"]
  - name: "auto add label=CI"
    conditions:
      - files~=^(ci/|.github/)
    actions:
      label:
        add: ["CI"]
  - name: "auto add label=Installation"
    conditions:
      - files~=^(tools/|setup.py)
    actions:
      label:
        add: ["Installation"]
  - name: "auto add label=mergify"
    conditions:
      - files~=^.mergify.yml
    actions:
      label:
        add: ["mergify"]
  - name: "auto add label=Docker"
    conditions:
      - files~=^docker/
    actions:
      label:
        add: ["Docker"]
