from typing import Dict, List, Optional, Tuple, Union

# adapted from https://github.com/espnet/espnet/blob/master/egs2/
#              owsm_v1/s2t1/local/utils.py
############################################
# Definitions of shared symbols and values #
############################################
SYMBOL_NA: str = "<na>"  # symbol denoting text is not available
SYMBOL_NOSPEECH: str = "<nospeech>"  # symbol denoting non-speech audio
SPEECH_MAX_LEN: float = 20  # max speech length in seconds
SPEECH_RESOLUTION: float = 0.02  # resolution in seconds
# all timestamp symbols
SYMBOLS_TIME: List[str] = [
    "<notimestamps>",
    *[
        f"<{i * SPEECH_RESOLUTION:.2f}>"
        for i in range(round(SPEECH_MAX_LEN / SPEECH_RESOLUTION) + 1)
    ],
]
TASK_TOKENS: List[str] = ["<asr>", "<pr>", "<g2p>", "<p2g>"]
LANGUAGES = {
    "<afr>": "Afrikaans",
    "<amh>": "Amharic",
    "<ara>": "Arabic",
    "<aze>": "Azerbaijani",
    "<bak>": "Bashkir",
    "<bel>": "Belarusian",
    "<ben>": "Bangla",
    "<bos>": "Bosnian",
    "<bul>": "Bulgarian",
    "<cat>": "Catalan",
    "<ceb>": "Cebuano",
    "<ces>": "Czech",
    "<cmn>": "Mandarin Chinese",
    "<cym>": "Welsh",
    "<dan>": "Danish",
    "<deu>": "German",
    "<ell>": "Greek",
    "<eng>": "English",
    "<est>": "Estonian",
    "<eus>": "Basque",
    "<fin>": "Finnish",
    "<fra>": "French",
    "<ful>": "Fula",
    "<gle>": "Irish",
    "<glg>": "Galician",
    "<hau>": "Hausa",
    "<hin>": "Hindi",
    "<hrv>": "Croatian",
    "<hun>": "Hungarian",
    "<ina>": "Interlingua",
    "<ind>": "Indonesian",
    "<isl>": "Icelandic",
    "<ita>": "Italian",
    "<jav>": "Javanese",
    "<jpn>": "Japanese",
    "<kat>": "Georgian",
    "<kaz>": "Kazakh",
    "<kin>": "Kinyarwanda",
    "<kir>": "Kyrgyz",
    "<kmr>": "Northern Kurdish",
    "<kor>": "Korean",
    "<lao>": "Lao",
    "<lit>": "Lithuanian",
    "<mal>": "Malayalam",
    "<mar>": "Marathi",
    "<mkd>": "Macedonian",
    "<mlt>": "Maltese",
    "<mon>": "Mongolian",
    "<mri>": "Māori",
    "<msa>": "Malay",
    "<mya>": "Burmese",
    "<nld>": "Dutch",
    "<nob>": "Norwegian Bokmål",
    "<nya>": "Nyanja",
    "<ori>": "Odia",
    "<orm>": "Oromo",
    "<pan>": "Punjabi",
    "<pol>": "Polish",
    "<por>": "Portuguese",
    "<ron>": "Romanian",
    "<rus>": "Russian",
    "<sin>": "Sinhala",
    "<skr>": "Saraiki",
    "<slk>": "Slovak",
    "<slv>": "Slovenian",
    "<sna>": "Shona",
    "<snd>": "Sindhi",
    "<som>": "Somali",
    "<spa>": "Spanish",
    "<srp>": "Serbian",
    "<swa>": "Swahili",
    "<swe>": "Swedish",
    "<tam>": "Tamil",
    "<tat>": "Tatar",
    "<tel>": "Telugu",
    "<tgk>": "Tajik",
    "<tha>": "Thai",
    "<tur>": "Turkish",
    "<uig>": "Uyghur",
    "<ukr>": "Ukrainian",
    "<urd>": "Urdu",
    "<uzb>": "Uzbek",
    "<vie>": "Vietnamese",
    "<xho>": "Xhosa",
    "<yor>": "Yoruba",
    "<yue>": "Cantonese",
    "<zul>": "Zulu",
}

PHONEME_VOCABULARY = {
    "a",
    "ã",
    "b",
    "bʰ",
    "bʲ",
    "bʷ",
    "bˠ",
    "bˤ",
    "c",
    "cʰ",
    "cʲ",
    "cʼ",
    "ç",
    "d",
    "dʰ",
    "dʲ",
    "dʷ",
    "dˠ",
    "dˤ",
    "d̪",
    "e",
    "ẽ",
    "f",
    "fʲ",
    "fʷ",
    "fˠ",
    "fˤ",
    "f̩",
    "h",
    "hʲ",
    "hˠ",
    "i",
    "ĩ",
    "j",
    "jˠ",
    "jˤ",
    "j̃",
    "j̩",
    "k",
    "kʰ",
    "kʲ",
    "kʷ",
    "kʼ",
    "l",
    "lʲ",
    "lˠ",
    "lˤ",
    "l̥",
    "l̩",
    "l̪",
    "l̴",
    "m",
    "mʲ",
    "mʷ",
    "mˠ",
    "mˤ",
    "m̥",
    "m̩",
    "n",
    "nʲ",
    "nˠ",
    "nˤ",
    "n̥",
    "n̩",
    "n̪",
    "o",
    "õ",
    "p",
    "pʰ",
    "pʲ",
    "pʷ",
    "pʼ",
    "pˠ",
    "q",
    "qʷ",
    "qʼ",
    "r",
    "rʲ",
    "rˠ",
    "rˤ",
    "r̥",
    "r̩",
    "s",
    "sʰ",
    "sʲ",
    "sʷ",
    "sʼ",
    "sˤ",
    "s̩",
    "s̪",
    "s̺",
    "t",
    "tʰ",
    "tʲ",
    "tʷ",
    "tʼ",
    "tˠ",
    "tˤ",
    "t̪",
    "u",
    "ũ",
    "v",
    "vʲ",
    "vˠ",
    "w",
    "wʲ",
    "wˠ",
    "w̃",
    "x",
    "xʲ",
    "y",
    "z",
    "zʲ",
    "zʷ",
    "zˠ",
    "zˤ",
    "æ",
    "ç",
    "ð",
    "ðˠ",
    "ðˤ",
    "ð̩",
    "ø",
    "ħ",
    "ŋ",
    "ŋʲ",
    "ŋ̥",
    "ŋ̩",
    "œ",
    "œ̃",
    "ǀ",
    "ǀʰ",
    "ǁ",
    "ǁʰ",
    "ǃ",
    "ǃʰ",
    "ɐ",
    "ɐˤ",
    "ɐ̃",
    "ɑ",
    "ɑ̃",
    "ɒ",
    "ɓ",
    "ɔ",
    "ɔˤ",
    "ɔ̃",
    "ɕ",
    "ɕʰ",
    "ɖ",
    "ɗ",
    "ɘ",
    "ə",
    "ə˞",
    "ə̃",
    "ɛ",
    "ɛˤ",
    "ɛ̃",
    "ɜ",
    "ɜ˞",
    "ɞ",
    "ɟ",
    "ɟʰ",
    "ɠ",
    "ɡ",
    "ɡʰ",
    "ɡʲ",
    "ɡʷ",
    "ɡ̃",
    "ɢ",
    "ɣ",
    "ɣʲ",
    "ɤ",
    "ɥ",
    "ɦ",
    "ɦʲ",
    "ɧ",
    "ɨ",
    "ɪ",
    "ɪˤ",
    "ɪ̃",
    "ɬ",
    "ɭ",
    "ɭʲ",
    "ɭ̩",
    "ɮ",
    "ɮʲ",
    "ɯ",
    "ɰ",
    "ɱ",
    "ɲ",
    "ɲ̥",
    "ɳ",
    "ɴ",
    "ɵ",
    "ɶ",
    "ɸ",
    "ɸʷ",
    "ɹ",
    "ɻ",
    "ɽ",
    "ɽʷ",
    "ɾ",
    "ɾʲ",
    "ɾˠ",
    "ʀ",
    "ʁ",
    "ʁ̩",
    "ʂ",
    "ʂʰ",
    "ʂʲ",
    "ʃ",
    "ʃʲ",
    "ʃʼ",
    "ʃˠ",
    "ʃ̩",
    "ʄ",
    "ʈ",
    "ʈʰ",
    "ʉ",
    "ʊ",
    "ʊˤ",
    "ʊ̃",
    "ʋ",
    "ʋʲ",
    "ʋ̥",
    "ʌ",
    "ʌ̃",
    "ʍ",
    "ʎ",
    "ʏ",
    "ʐ",
    "ʐʲ",
    "ʑ",
    "ʒ",
    "ʒʲ",
    "ʒ̩",
    "ʔ",
    "ʕ",
    "ʙ",
    "ʝ",
    "β",
    "θ",
    "χ",
}
