builder:
  dataset_path: /scratch/elec/t405-puhe/c/librispeech
  manifest_path: #insert if available /m/teamwork/t40511_asr/p/raissit1/lhotse_manifests
  required_splits:
    - train-clean-100
    - dev-clean
    - dev-other
    - test-clean
    - test-other

dataset:
  supported_splits:
    - train-clean-100
    - dev-clean
    - dev-other
    - test-clean
    - test-other
