#!/bin/bash
# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail

log() {
    local fname=${BASH_SOURCE[1]##*/}
    echo -e "$(date '+%Y-%m-%dT%H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $@"
}
help_message=$(cat << EOF
$0 --train-set <train_set_name> --dev-set <dev_set_name> --eval_sets <eval_set_names> --srctexts <srctexts >

Options:
    --nj (int): The number of parallel jobs
    --stage (int): Processes starts from the specifed stage.
    --stop-stage (int): Processes is stopped at the specifed stage.
    --nlsyms: non-linguistic symbol list
    --oov (str): Out of vocabrary symbol. The default is "<unk>"
    --token_mode (str): The tokenize level. Select either one of "bpe", "char" or "word". The default is "bpe"
    --nbpe (int):
EOF
)
SECONDS=0


## general configuration
stage=1
stop_stage=100

nj=50
decode_nj=50
# number of gpus ("0" uses cpu, otherwise use gpu)
ngpu=1
gpu_decode=false


## The options for prepare.sh
audio_format=flac
fs=16k

# token_mode=char
token_mode=bpe

nbpe=30
# bpemode (unigram or bpe)
bpemode=unigram
bpe_input_sentence_size=100000000
oov="<unk>"



## The options for training
exp=exp

# Add suffix to the result dir for lm training
lm_tag=
lm_config=
lm_preprocess_config=
use_word_lm=false
word_vocab_size=10000

# Add suffix to the result dir for asr training
asr_tag=
asr_config=
asr_preprocess_config=

decode_config=

# [Task depented] Set the datadir name created by local/data.sh
train_set=
dev_set=
eval_sets=
# Used for the training of BPE and the creation of a vocabulary list
srctexts=


log "$0 $*"
. utils/parse_options.sh
. ./path.sh
. ./cmd.sh

if [ $# -ne 0 ]; then
    log "Error: No positional arguments are required."
    log "${help_message}"
    exit 2
fi

[ -z "${train_set}" ] && { log "Error: --train_set is required"; log "${help_message}"; exit 2; };
[ -z "${dev_set}" ] && { log "Error: --dev_set is required"; log "${help_message}"; exit 2; };
[ -z "${eval_sets}" ] && { log "Error: --eval_sets is required"; log "${help_message}"; exit 2; };
[ -z "${srctexts}" ] && { log "Error: --srctexts is required"; log "${help_message}"; exit 2; };

lm_train_text="data/${train_set}/text"
lm_dev_text="data/${dev_set}/text"

data_format=data_format
data_tokenized="data_tokenized_${token_mode}"
if ${use_word_lm}; then
    data_lm=data_${token_mode}_lm
else
    data_lm=data_word_lm
fi

token_listdir=data/token_list
bpedir="${token_listdir}/bpe_${bpemode}${nbpe}"
bpeprefix="${bpedir}"/model
bpemodel="${bpeprefix}".model
bpetoken_list="${bpedir}"/tokens.txt
chartoken_list="${token_listdir}"/char/tokens.txt
wordtoken_list="${token_listdir}"/word/tokens.txt

nlsyms_txt=data/lang_1char/non_lang_syms.txt

if ${use_word_lm}; then
    lm_token_mode="word"
else
    lm_token_mode="${token_mode}"
fi



if [ ${stage} -le 1 ] && [ ${stop_stage} -ge 1 ]; then
    log "stage 1: Data preparation for data/${train_set}, data/${dev_set}, etc."
    local/data.sh
fi

# non-linguistic symbol list if existing
# (should be generated by local/data.sh)
if [ -f "${nlsyms_txt}" ]; then
    nlsyms="$(<${nlsyms_txt})"
else
    nlsyms=
fi


if [ ${stage} -le 2 ] && [ ${stop_stage} -ge 2 ]; then
    log "stage 2: Format wav.scp: data/ -> ${data_format}/"

    # ====== Recreating "wav.scp" ======
    # Kaldi-wav.scp, which can describe the file path with unix-pipe, like "cat /some/path |",
    # shouldn't be used in training process.
    # "format_wav_scp.sh" dumps such pipe-style-wav to real audio file
    # and also it can also change the audio-format and sampling rate.
    # If nothing is need, then format_wav_scp.sh does nothing:
    # i.e. the input file format and rate is same as the output.

    for dset in "${train_set}" "${dev_set}" ${eval_sets}; do
        utils/copy_data_dir.sh data/"${dset}" "${data_format}/${dset}"
        scripts/audio/format_wav_scp.sh --nj "${nj}" --cmd "${train_cmd}" \
            --audio-format "${audio_format}" --fs "${fs}" \
            "data/${dset}/wav.scp" "${data_format}/${dset}"
    done
fi


if [ "${token_mode}" = bpe ]; then
    token_list="${bpetoken_list}"
elif [ "${token_mode}" = char ]; then
    token_list="${chartoken_list}"
    bpemodel=""
else
    log "Error: not supported --token_mode '${token_mode}'"
    exit 2
fi


if [ ${stage} -le 3 ] && [ ${stop_stage} -ge 3 ]; then
    if [ "${token_mode}" = bpe ]; then
        log "stage 3: Generate token_list from ${srctexts} using BPE"

        mkdir -p "${bpedir}"
        cat ${srctexts} | cut -f 2- -d" "  > "${bpedir}"/train.txt

        spm_train \
            --input="${bpedir}"/train.txt \
            --vocab_size="${nbpe}" \
            --model_type="${bpemode}" \
            --model_prefix="${bpeprefix}" \
            --input_sentence_size="${bpe_input_sentence_size}"

        echo "<unk>" > "${token_list}"
        cat ${srctexts} | cut -f 2- -d" " | \
            spm_encode --model="${bpemodel}" --output_format=piece | \
                tr ' ' '\n' | sort -u >> "${token_list}"

    elif [ "${token_mode}" = char ]; then
        log "stage 3: Generate character level token_list from ${srctexts}"
        mkdir -p "$(dirname ${token_list})"


        echo "<unk>" > "${token_list}"
        if [ -n "${nlsyms}" ]; then
            cat ${srctexts} | pyscripts/text/text2token.py -s 1 -n 1 -l "${nlsyms}"  \
                | cut -f 2- -d" " | tr " " "\n" | sort -u \
                | grep -v -e '^\s*$' >> "${token_list}"
        else
            cat ${srctexts} | pyscripts/text/text2token.py -s 1 -n 1 \
                | cut -f 2- -d" " | tr " " "\n" | sort -u \
                | grep -v -e '^\s*$' >> "${token_list}"
        fi
    else
        log "Error: not supported --token_mode '${token_mode}'"
        exit 2
    fi


    if ${use_word_lm}; then
        log "Generate word level token_list from ${srctexts}"
        mkdir -p "$(dirname ${token_list})"
        log "Not yet"
        exit 1

        # TODO(kamo): tokens.txt instead of dict
        # cat ${srctexts} | text2vocabulary.py -s ${word_vocab_size} -o ${dict}
    fi

fi


if [ ${stage} -le 4 ] && [ ${stop_stage} -ge 4 ]; then
    log "stage 4: Create tokens from text: token_list=${token_list}"

    for dset in "${train_set}" "${dev_set}" ${eval_sets}; do
        # 1. Copy datadir
        utils/copy_data_dir.sh "${data_format}/${dset}" "${data_tokenized}/${dset}"
        # Copying extended files from Kaldi-datadir
        [ -e "${data_format}/${dset}/utt2num_samples" ] && \
            cp "${data_format}/${dset}/utt2num_samples" "${data_tokenized}/${dset}/utt2num_samples"

        scripts/asr/prepare_token.sh \
            --mode "${token_mode}" --bpemodel "${bpemodel}" \
                "${data_format}/${dset}/text" "${token_list}" "${data_tokenized}/${dset}"
    done

    scripts/asr/prepare_token.sh \
        --mode "${lm_token_mode}" --bpemodel "${bpemodel}" \
            "${lm_train_text}" "${token_list}" "${data_lm}"/train
    scripts/asr/prepare_token.sh \
        --mode "${lm_token_mode}" --bpemodel "${bpemodel}" \
            "${lm_dev_text}" "${token_list}" "${data_lm}"/dev
fi

# ========================== Data preparation is done here. ==========================


lm_exp="${exp}/${lm_token_mode}_lm_train${lm_tag}"
if [ ${stage} -le 5 ] && [ ${stop_stage} -ge 5 ]; then
    log "stage 5: LM Training: train_set=${data_lm}/train, dev_set=${data_lm}/dev"

    _opts=
    if [ -n "${lm_config}" ]; then
        # To generate the config file: e.g.
        #   % python -m espnet2.bin.lm_train --print_config --optimizer adam --lm transformer
        _opts+="--config ${lm_config} "
    fi
    if [ -n "${lm_preprocess_config}" ]; then
        _opts+="--train_preprosess input=${lm_preprocess_config} "
        _opts+="--eval_preprosess input=${lm_preprocess_config} "
    fi

    log "LM training started... log: '${lm_exp}/train.log'"
    ${cuda_cmd} --gpu "${ngpu}" "${lm_exp}"/train.log \
        python3 -m espnet2.bin.lm_train \
            --ngpu "${ngpu}" \
            --batch_size=1 \
            --token_list "${data_lm}/train/tokens.txt" \
            --train_data_path_and_name_and_type "${data_lm}/train/token_int,input,text_int" \
            --eval_data_path_and_name_and_type "${data_lm}/dev/token_int,input,text_int" \
            --train_shape_file "${data_lm}/train/token_shape" \
            --eval_shape_file "${data_lm}/dev/token_shape" \
            --max_length 150 \
            ${_opts} \
            --output_dir "${lm_exp}"

   # TODO(kamo): calculate perplexity
fi


asr_exp="${exp}/asr_train${asr_tag}"
if [ ${stage} -le 6 ] && [ ${stop_stage} -ge 6 ]; then
    asr_train_dir="${data_tokenized}/${train_set}"
    asr_dev_dir="${data_tokenized}/${dev_set}"
    log "stage 6: ASR Training: train_set=${asr_train_dir}, dev_set=${asr_dev_dir}"

    _opts=
    if [ -n "${asr_config}" ]; then
        # To generate the config file: e.g.
        #   % python -m espnet2.bin.asr_train --print_config --optimizer adam --encoder_decoder transformer
        _opts+="--config ${asr_config} "
    fi
    if [ -n "${asr_preprocess_config}" ]; then
        # syntax: --train_preprosess {key}={yaml file or yaml string}
        _opts+="--train_preprosess input=${asr_preprocess_config} "
         _opts+="--eval_preprosess input=${asr_preprocess_config} "
    fi

    # FIXME(kamo): data_path_and_name_and_type looks not smart?
    # another idea is
    # --train_data_path <path>
    # --train_data_name <name>
    # --train_data_type <type>
    # --train_data_path <path>
    # --train_data_name <name>
    # --train_data_type <type>
    # ...

    log "ASR training started... log: '${asr_exp}/train.log'"
    ${cuda_cmd} --gpu "${ngpu}" "${asr_exp}"/train.log \
        python3 -m espnet2.bin.asr_train \
            --ngpu "${ngpu}" \
            --batch_size=1 \
            --token_list "${asr_train_dir}/tokens.txt" \
            --train_data_path_and_name_and_type "${asr_train_dir}/wav.scp,input,sound" \
            --train_data_path_and_name_and_type "${asr_train_dir}/token_int,output,text_int" \
            --eval_data_path_and_name_and_type "${asr_dev_dir}/wav.scp,input,sound" \
            --eval_data_path_and_name_and_type "${asr_dev_dir}/token_int,output,text_int" \
            --train_shape_file "${asr_train_dir}/utt2num_samples" \
            --train_shape_file "${asr_train_dir}/token_shape" \
            --eval_shape_file "${asr_dev_dir}/utt2num_samples" \
            --eval_shape_file "${asr_dev_dir}/token_shape" \
            --max_length 80000 \
            --max_length 150 \
            ${_opts} \
            --output_dir "${asr_exp}"

fi


if [ ${stage} -le 7 ] && [ ${stop_stage} -ge 7 ]; then
    # FIXME(kamo): Too long and dirty.

    log "stage 7: Decoding"

    if ${gpu_decode}; then
        _cmd=${cuda_cmd}
        _ngpu=1
    else
        _cmd=${decode_cmd}
        _ngpu=0
    fi

    _opts=
    if [ -n "${decode_config}" ]; then
        _opts+="--config ${decode_config} "
    fi
    if [ -n "${asr_preprocess_config}" ]; then
        _opts+="--preprosess input=${asr_preprocess_config} "
    fi

    if [ -f "${asr_exp}"/acc.best.pt ]; then
        _asr_model_file="${asr_exp}"/acc.best.pt
    else
        _asr_model_file="${asr_exp}"/loss.best.pt
    fi

    for dset in ${eval_sets}; do
        _data="${data_tokenized}/${dset}"
        _dir="${asr_exp}/decode_${dset}"
        _logdir="${_dir}/logdir"
        mkdir -p "${_logdir}"

        # 1. Split the key file
        key_file=${_data}/wav.scp
        split_scps=""
        _nj=$((${decode_nj}<$(<${key_file} wc -l)?${decode_nj}:$(<${key_file} wc -l)))
        for n in $(seq ${_nj}); do
            split_scps+=" ${_logdir}/keys.${n}.scp"
        done
        utils/split_scp.pl "${key_file}" ${split_scps}

        # 2. Submit decoding jobs
        log "Decoding started... log: '${_logdir}/asr_recog.*.log'"
        ${_cmd} --gpu "${_ngpu}" JOB=1:"${_nj}" "${_logdir}"/asr_recog.JOB.log \
            python3 -m espnet2.bin.asr_recog \
                --ngpu "${_ngpu}" \
                --data_path_and_name_and_type "${_data}/wav.scp,input,sound" \
                --key_file "${_logdir}"/keys.JOB.scp \
                --asr_train_config "${asr_exp}"/config.yaml \
                --asr_model_file "${_asr_model_file}" \
                --lm_train_config "${lm_exp}"/config.yaml \
                --lm_file "${lm_exp}"/loss.best.pt \
                ${_opts} \
                --output_dir "${_logdir}"/output.JOB

        # 3. Concatenates the output files from each jobs
        for f in token token_int score; do
            for i in $(seq "${_nj}"); do
                cat "${_logdir}/output.${i}/1best_recog/${f}"
            done | LC_ALL=C sort -k1 >"${_dir}/${f}"
        done

        # 4. Convert token to text
        if [ ! -f "${_data}/token_mode" ]; then
            log "Error: No such file: '${_data}/token_mode'. Did you run prepare_token.sh?"
            exit 1
        fi

        _token_mode="$(<${_data}/token_mode)"

        if [ "${_token_mode}" = bpe ]; then
            paste <(<${_dir}/token cut -f 1 -d" ") \
                <(<${_dir}/token cut -f 2- -d" " \
                  | spm_decode --model=${bpemodel} --input_format=piece \
                  | sed -e "s/▁/ /g") \
                >  ${_dir}/text

        elif [ "${_token_mode}" = char ]; then
            paste <(<${_dir}/token cut -f 1 -d" ") \
                <(<${_dir}/token cut -f 2- -d" "  \
                  | sed -e 's/ //' \
                  | sed -e 's/<space>/ /' \
                  ) \
                >  ${_dir}/text
        else
            log "Error: not supported --token_mode '${_token_mode}'"
            exit 2
        fi

    done
fi


if [ ${stage} -le 8 ] && [ ${stop_stage} -ge 8 ]; then
    log "stage 8: Scoring"

    for dset in ${eval_sets}; do
        _data="${data_tokenized}/${dset}"
        _dir="${asr_exp}/decode_${dset}"

        _token_mode="$(<${_data}/token_mode)"
        if [ "${_token_mode}" = char ]; then
            _modes="cer wer"
        else
            _modes="wer"
        fi


        for _mode in ${_modes}; do
            if [ "${_mode}" = wer ]; then
                text=text
            else
                text=token
            fi

            _scoredir="${_dir}/score_${_mode}"
            mkdir -p ${_scoredir}

            # 1. Covert text to "trn" format
            <${_data}/${text} \
                awk ' { s=""; for(i=2;i<=NF;++i){ s=s $i " "; }; print s "(" $1 ")"; } ' \
                    >${_scoredir}/ref.trn
            <${_dir}/${text} \
                awk ' { s=""; for(i=2;i<=NF;++i){ s=s $i " "; }; print s "(" $1 ")"; } ' \
                    >${_scoredir}/hyp.trn

            if [ "${_mode}" = char ] && [ -n "${nlsyms}" ]; then
                for f in ref.trn hyp.trn; do
                    cp "${_scoredir}/${f}" "${_scoredir}/${f}.org"
                    pyscripts/text/filt.py -v "${nlsyms}" "${_scoredir}/${f}.org" \
                        >"${_scoredir}/${f}"
                done
            fi

            # 2. Sclite
            sclite \
                -r "${_scoredir}/ref.trn" trn \
                -h "${_scoredir}/hyp.trn" trn \
                -i rm -o all stdout > "${_scoredir}/result.txt"

            log "Write ${_mode} result in ${_scoredir}/result.txt"
            grep -e Avg -e SPKR -m 2 "${_scoredir}/result.txt"
        done

    done

fi

log "Successfully finished. [elapsed=${SECONDS}s]"
