dataset:
  recipe_dir: ${recipe_dir}
  test:
    - name: test
      data_src_args:
        split: test
        include_utt_id: true

model:
  _target_: espnet2.bin.tts_inference.Text2Speech
  train_config: ${exp_dir}/config.yaml
  model_file: ${exp_dir}/last.ckpt

output_artifacts:
  wav:
    type: wav
    sample_rate: 16000
