##########################################################
#                 METRIC SCORING SETTING                 #
##########################################################
# Quick usage:
#   python run.py --stages measure --metrics_config conf/metrics.yaml
#
##########################################################
#                    PATHS AND INPUTS                    #
##########################################################
inference_dir: ${exp_dir}/inference

##########################################################
#                    METRIC DEFINITION                   #
##########################################################
metrics:
  - metric:
      _target_: espnet3.systems.asr.metrics.wer.WER
      clean_types:

  - metric:
      _target_: espnet3.systems.asr.metrics.cer.CER
      clean_types:
