# Mini AN4 ASR scoring config for ESPnet3 integration tests.

dataset:
  test:
    - name: test
      dataset:
        _target_: src.dataset.MiniAN4Dataset
        manifest_path: ${dataset_dir}/manifest/test.tsv

metrics:
  - metric:
      _target_: espnet3.systems.asr.metrics.wer.WER
      clean_types:

  - metric:
      _target_: espnet3.systems.asr.metrics.cer.CER
      clean_types:
