#!/usr/bin/env bash
# Nahuatl ASR — OWSM v4 fine-tuning recipe
# Thin wrapper around egs2/TEMPLATE/s2t1/s2t.sh.
#
# Prerequisites (one-time setup):
#   1. Download espnet/owsm_v4_medium_1B from HuggingFace into
#      <repo_root>/model_cache/owsm_v4_medium_1B/
#   2. Patch the checkpoint and generate the extended token list:
#        python local/init_new_tokens.py \
#          --src_ckpt  ../../../../model_cache/owsm_v4_medium_1B/exp/.../valid.loss.best.pth \
#          --out_ckpt  ../../../../model_cache/owsm_v4_medium_1B_nahuatl/valid.loss.best.pth \
#          --src_config ../../../../model_cache/owsm_v4_medium_1B/exp/.../config.yaml \
#          --out_token_list data/token_list/bpe_unigram50000/tokens.txt
#   3. Prepare the HuggingFace dataset and run local/data.sh (Stage 1).
#
# Quick usage:
#   bash run.sh                        # full pipeline
#   bash run.sh --stage 11 --stop_stage 11   # train only
#   max_epoch=1 num_iters_per_epoch=20 log_interval=1 bash run.sh --stage 11 --stop_stage 11  # debug
set -euo pipefail

RECIPE_DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
cd "$RECIPE_DIR"
. cmd.sh
. path.sh

# ── Recipe configuration ────────────────────────────────────────────────────
train_set="nahuatl_train"
valid_set="nahuatl_valid"
# Only the three single-region test sets: espnet2 decoding applies one --lang_sym
# to the whole run, so a mixed-region set cannot be decoded correctly. decode.sh
# decodes each region with its own lang_sym and combines them for the aggregate
# score (which is what a mixed test set would measure).
test_sets="nahuatl_hidalgo_test nahuatl_orizaba_zongolica_test nahuatl_zacatlan_tepetzintla_test"

s2t_config="conf/tuning/train_owsm_v4_nahuatl.yaml"

MODEL_DIR=$(realpath "../../../../model_cache/owsm_v4_medium_1B_nahuatl")
UPSTREAM_DIR=$(realpath "../../../../model_cache/owsm_v4_medium_1B")
UPSTREAM_FEATS_STATS="$UPSTREAM_DIR/exp/s2t_stats_raw_bpe50000/train/feats_stats.npz"
# Use the PATCHED BPE model, which adds the three region tokens as SentencePiece
# user-defined symbols so they tokenize as single pieces (id 50002-50004) instead
# of being split into subwords. init_new_tokens.py builds it from the upstream one.
NAHUATL_BPE="$MODEL_DIR/data/token_list/bpe_unigram50000/bpe.model"

# s2t.sh expects BPE model at data/token_list/bpe_unigram50000/bpe.model
TOKEN_LIST_DIR="data/token_list/bpe_unigram50000"
if [ ! -f "$NAHUATL_BPE" ]; then
    echo "ERROR: patched BPE model not found at $NAHUATL_BPE"
    echo "Run init_new_tokens.py (see header) to build it from the upstream model."
    exit 1
fi
mkdir -p "$TOKEN_LIST_DIR"
ln -sf "$(realpath "$NAHUATL_BPE")" "$TOKEN_LIST_DIR/bpe.model"

# Fine-tuning must reuse OWSM's global-mvn feature statistics: the model was
# pretrained with these, and collect_stats (stage 10) does not regenerate them
# for a raw-audio S2T model whose frontend lives inside the network. Symlink the
# upstream feats_stats.npz into the stats dir so stage 11 (normalize=global_mvn)
# finds it. Placed here so it survives stage 10, which writes only shape files.
STATS_TRAIN_DIR="exp/s2t_stats_raw_bpe50000/train"
if [ -f "$UPSTREAM_FEATS_STATS" ] && [ ! -e "$STATS_TRAIN_DIR/feats_stats.npz" ]; then
    mkdir -p "$STATS_TRAIN_DIR"
    ln -sf "$(realpath "$UPSTREAM_FEATS_STATS")" "$STATS_TRAIN_DIR/feats_stats.npz"
fi

# Verify the extended token list exists (generated by init_new_tokens.py)
if [ ! -f "$TOKEN_LIST_DIR/tokens.txt" ]; then
    echo "ERROR: $TOKEN_LIST_DIR/tokens.txt not found."
    echo "Run init_new_tokens.py with --src_config and --out_token_list (see header)."
    exit 1
fi

# Verify the patched checkpoint exists
if [ ! -f "$MODEL_DIR/valid.loss.best.pth" ]; then
    echo "ERROR: Patched checkpoint not found at $MODEL_DIR/valid.loss.best.pth"
    echo "Run init_new_tokens.py (see header)."
    exit 1
fi

# Debug overrides: set these env vars to limit training
# e.g.: max_epoch=1 num_iters_per_epoch=20 log_interval=1 bash run.sh --stage 11 --stop_stage 11
_s2t_args="--init_param ${MODEL_DIR}/valid.loss.best.pth"
[ -n "${max_epoch:-}" ]            && _s2t_args+=" --max_epoch $max_epoch"
[ -n "${num_iters_per_epoch:-}" ]  && _s2t_args+=" --num_iters_per_epoch $num_iters_per_epoch"
[ -n "${log_interval:-}" ]         && _s2t_args+=" --log_interval $log_interval"

# ── Delegate to TEMPLATE s2t.sh ─────────────────────────────────────────────
./s2t.sh \
    --use_lm false \
    --ngpu 1 \
    --feats_type raw \
    --audio_format wav \
    --fs 16k \
    --min_wav_duration 0.1 \
    --max_wav_duration 30.5 \
    --token_type bpe \
    --nbpe 50000 \
    --s2t_config "${s2t_config}" \
    --s2t_args "${_s2t_args}" \
    --train_set "${train_set}" \
    --valid_set "${valid_set}" \
    --test_sets "${test_sets}" \
    --skip_stages "5 6" \
    "$@"
