#!/usr/bin/env bash
# Nahuatl ASR — OWSM v4 fine-tuning recipe
# Thin wrapper around egs2/TEMPLATE/s2t1/s2t.sh.
#
# Prerequisites (one-time setup):
#   1. Download espnet/owsm_v4_medium_1B from HuggingFace into
#      <repo_root>/model_cache/owsm_v4_medium_1B/
#   2. Patch the checkpoint and generate the extended token list:
#        python local/init_new_tokens.py \
#          --src_ckpt  ../../../../model_cache/owsm_v4_medium_1B/exp/.../valid.loss.best.pth \
#          --out_ckpt  ../../../../model_cache/owsm_v4_medium_1B_nahuatl/valid.loss.best.pth \
#          --src_config ../../../../model_cache/owsm_v4_medium_1B/exp/.../config.yaml \
#          --out_token_list data/token_list/bpe_unigram50000/tokens.txt \
#          --src_bpe   ../../../../model_cache/owsm_v4_medium_1B/data/token_list/bpe_unigram50000/bpe.model \
#          --out_bpe   ../../../../model_cache/owsm_v4_medium_1B_nahuatl/data/token_list/bpe_unigram50000/bpe.model
#   3. Prepare the HuggingFace dataset and run local/data.sh (Stage 1).
#
# Quick usage:
#   bash run.sh                        # full pipeline
#   bash run.sh --stage 11 --stop_stage 11   # train only
#   max_epoch=1 num_iters_per_epoch=20 log_interval=1 bash run.sh --stage 11 --stop_stage 11  # debug
set -euo pipefail

RECIPE_DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
cd "$RECIPE_DIR"
. cmd.sh
. path.sh

# ── Recipe configuration ────────────────────────────────────────────────────
train_set="nahuatl_train"
valid_set="nahuatl_valid"
# Only the three single-region test sets: espnet2 decoding applies one --lang_sym
# to the whole run, so a mixed-region set cannot be decoded correctly. decode.sh
# decodes each region with its own lang_sym and combines them for the aggregate
# score (which is what a mixed test set would measure).
test_sets="nahuatl_hidalgo_test nahuatl_orizaba_zongolica_test nahuatl_zacatlan_tepetzintla_test"

s2t_config="conf/train.yaml"

MODEL_DIR=$(realpath "../../../../model_cache/owsm_v4_medium_1B_nahuatl")
UPSTREAM_DIR=$(realpath "../../../../model_cache/owsm_v4_medium_1B")
UPSTREAM_FEATS_STATS="$UPSTREAM_DIR/exp/s2t_stats_raw_bpe50000/train/feats_stats.npz"
# Use the PATCHED BPE model, which adds the three region tokens as SentencePiece
# user-defined symbols so they tokenize as single pieces (id 50002-50004) instead
# of being split into subwords. init_new_tokens.py builds it from the upstream one.
NAHUATL_BPE="$MODEL_DIR/data/token_list/bpe_unigram50000/bpe.model"

# s2t.sh expects BPE model at data/token_list/bpe_unigram50000/bpe.model
TOKEN_LIST_DIR="data/token_list/bpe_unigram50000"
if [ ! -f "$NAHUATL_BPE" ]; then
    echo "ERROR: patched BPE model not found at $NAHUATL_BPE"
    echo "Run init_new_tokens.py (see header) to build it from the upstream model."
    exit 1
fi
mkdir -p "$TOKEN_LIST_DIR"
ln -sf "$(realpath "$NAHUATL_BPE")" "$TOKEN_LIST_DIR/bpe.model"

# Fine-tuning must reuse OWSM's global-MVN feature statistics (the model was
# pretrained with them). collect_stats (stage 10) with global_mvn runs
# aggregate_stats_dirs, which WRITES train/feats_stats.npz into the stats dir —
# so a symlink pre-placed there would be overwritten (via the symlink) with
# Nahuatl-only statistics before stage 11 reads it. Install the pretrained
# symlink only AFTER stage 10 and BEFORE stage 11 (the split at the delegation
# below), overwriting whatever collect_stats produced.
STATS_TRAIN_DIR="exp/s2t_stats_raw_bpe50000/train"
install_feats_stats() {
    # Called only on training paths. Require the pretrained stats: without them
    # stage 11 would silently fine-tune on the wrong (Nahuatl-only) global-MVN
    # statistics stage 10 produced.
    if [ ! -f "$UPSTREAM_FEATS_STATS" ]; then
        echo "ERROR: pretrained feature statistics not found at" >&2
        echo "  $UPSTREAM_FEATS_STATS" >&2
        echo "Fine-tuning requires OWSM's global-MVN stats; download the" \
             "pretrained model into model_cache/ (see header) before training." >&2
        exit 1
    fi
    mkdir -p "$STATS_TRAIN_DIR"
    ln -sf "$(realpath "$UPSTREAM_FEATS_STATS")" \
        "$STATS_TRAIN_DIR/feats_stats.npz"
}

# Verify the extended token list exists (generated by init_new_tokens.py)
if [ ! -f "$TOKEN_LIST_DIR/tokens.txt" ]; then
    echo "ERROR: $TOKEN_LIST_DIR/tokens.txt not found."
    echo "Run init_new_tokens.py with --src_config and --out_token_list (see header)."
    exit 1
fi
# init_new_tokens.py writes the patched checkpoint even when the token list is
# not regenerated (--src_config/--out_token_list omitted). Since stages 5-6 are
# skipped, s2t.sh feeds this existing token list straight to the trainer, so a
# stale list (without the region tokens) would silently mismatch the checkpoint
# that has the three extra rows. Fail early unless the region tokens are present.
for _t in "<nah_hid>" "<nah_ozg>" "<nah_ztp>"; do
    if ! grep -qxF "$_t" "$TOKEN_LIST_DIR/tokens.txt"; then
        echo "ERROR: region token $_t missing from $TOKEN_LIST_DIR/tokens.txt."
        echo "The token list is stale for the patched checkpoint; regenerate it"
        echo "with init_new_tokens.py --src_config --out_token_list (see header)."
        exit 1
    fi
done

# Verify the patched checkpoint exists
if [ ! -f "$MODEL_DIR/valid.loss.best.pth" ]; then
    echo "ERROR: Patched checkpoint not found at $MODEL_DIR/valid.loss.best.pth"
    echo "Run init_new_tokens.py (see header)."
    exit 1
fi

# Debug overrides: set these env vars to limit training
# e.g.: max_epoch=1 num_iters_per_epoch=20 log_interval=1 bash run.sh --stage 11 --stop_stage 11
_s2t_args="--init_param ${MODEL_DIR}/valid.loss.best.pth"
[ -n "${max_epoch:-}" ]            && _s2t_args+=" --max_epoch $max_epoch"
[ -n "${num_iters_per_epoch:-}" ]  && _s2t_args+=" --num_iters_per_epoch $num_iters_per_epoch"
[ -n "${log_interval:-}" ]         && _s2t_args+=" --log_interval $log_interval"

# ── Delegate to TEMPLATE s2t.sh ─────────────────────────────────────────────
s2t_opts=(
    --use_lm false
    --ngpu 1
    --feats_type raw
    --audio_format wav
    --fs 16k
    --min_wav_duration 0.1
    --max_wav_duration 30.5
    --token_type bpe
    --nbpe 50000
    --s2t_config "${s2t_config}"
    --s2t_args "${_s2t_args}"
    --train_set "${train_set}"
    --valid_set "${valid_set}"
    --test_sets "${test_sets}"
    --skip_stages "5 6"
)

# Requested stage range (run.sh defaults: full pipeline through training).
start_stage=1
stop_stage=11
_prev=""
for _a in "$@"; do
    [ "$_prev" = "--stage" ]      && start_stage="$_a"
    [ "$_prev" = "--stop_stage" ] && stop_stage="$_a"
    _prev="$_a"
done

if [ "${start_stage}" -le 10 ] && [ "${stop_stage}" -ge 11 ]; then
    # Training run that also builds stats: split around collect_stats (stage 10)
    # so its aggregate step cannot clobber the pretrained feats_stats.npz through
    # the symlink. Trailing --stage/--stop_stage win over any in "$@".
    ./s2t.sh "${s2t_opts[@]}" "$@" --stop_stage 10          # data + collect_stats
    install_feats_stats                                     # pretrained global-MVN
    # Train only. s2t.sh's decode (12-13) applies one --lang_sym to the whole
    # run, which is wrong for our three region test sets; evaluate per region
    # with decode.sh instead.
    ./s2t.sh "${s2t_opts[@]}" "$@" --stage 11 --stop_stage 11
elif [ "${start_stage}" -le 11 ] && [ "${stop_stage}" -ge 11 ]; then
    # Training only (stage 10 already done in a prior run): install the
    # pretrained stats (overwriting any Nahuatl stats from that stage 10), then
    # delegate.
    install_feats_stats
    ./s2t.sh "${s2t_opts[@]}" "$@"
else
    # No training in range (e.g. decode.sh: --stage 12 --stop_stage 13, or a
    # data-prep-only run): the trained model's config already carries its stats,
    # so do not touch feats_stats here.
    ./s2t.sh "${s2t_opts[@]}" "$@"
fi
