##########################################################
#                   Inference SETTING                    #
##########################################################
# Common usage:
#   python run.py --stages infer \
#       --training_config conf/training_asr_transformer.yaml \
#       --inference_config conf/inference.yaml
##########################################################
#                    DATASET DEFINITION                  #
##########################################################
dataset:
  test:
    - name: dev-clean
      data_src_args:
        split: dev-clean
    - name: dev-other
      data_src_args:
        split: dev-other
    - name: test-clean
      data_src_args:
        split: test-clean
    - name: test-other
      data_src_args:
        split: test-other

##########################################################
#                    MODEL AND OUTPUT                    #
##########################################################
model:
  _target_: egs3.librispeech_100.asr.src.granite_speech.GraniteSpeechInferenceSession
  model_tag_or_path: ${exp_dir}/hf
  user_prompt: "<|audio|>transcribe the speech with proper punctuation and capitalization."

input_key: speech
output_fn: src.inference.build_output
