#!/bin/bash


. utils/parse_options.sh

if [ $# -ne 1 ]; then
    echo "Usage: $0 exp/xxx" 1>&2
    echo ""
    echo "Show the system environments and the evaluation results in Markdown format."
    exit 1
else
  exp=$1
fi

[ -f ./path.sh ] && . ./path.sh
set -euo pipefail


cat << EOF
<!-- Generated by $0 -->
# RESULTS
## Environments
- date: \`$(LC_ALL=C date)\`
EOF

python << EOF
import sys, espnet, chainer, torch
pyversion = sys.version.replace('\n', ' ')

print(f"""- python version: \`{pyversion}\`
- espnet version: \`espnet {espnet.__version__}\`
- pytorch version: \`pytorch {torch.__version__}\`""")
EOF

cat << EOF
- Git hash: \`$(git rev-parse HEAD)\`
  - Commit date: \`$(git log -1 --format='%cd')\`

EOF


if [[ -f ${exp}/RESULTS.TXT ]]; then
  grep ^config "${exp}"/config.yaml
  cat "${exp}"/RESULTS.TXT
fi


