##########################################################
#                   INFERENCE SETTING                    #
##########################################################
# Common usage:
#   python run.py --stages infer \
#       --training_config conf/training.yaml \
#       --inference_config conf/inference.yaml

##########################################################
#                    DATASET DEFINITION                  #
##########################################################
dataset:
  test:
    - name: dev
      data_src_args:
        split: dev
        data_dir: ${data_dir}/voxlingua107
        sample_rate: 16000

##########################################################
#                    MODEL AND OUTPUT                    #
##########################################################
model:
  _target_: espnet3.systems.esp2_lid.inference.Speech2Language
  lid_train_config: ${exp_dir}/config.yaml
  lid_model_file: ${exp_dir}/valid.accuracy.best.pth
  lang2utt: ${stats_dir}/train/lang2utt
  dtype: float32

input_key: speech
output_keys:
  - hyp
  - ref
idx_key: utt_id
batch_size: 4
output_fn: src.inference.build_output
