<!-- Generated by /export/c04/jiatong/tools/espnet_update/espnet/utils/show_result.sh -->
# RESULTS
## Environments
- date: `Tue Dec  1 11:11:54 EST 2020`
- python version: `3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]`
- espnet version: `espnet 0.9.2`
- chainer version: `chainer 6.0.0`
- pytorch version: `pytorch 1.6.0`
- Git hash: `a0075233a29d7e2f5a965c2123f5fda8c718fd35`
  - Commit date: `Mon Nov 30 13:25:15 2020`

## train_cy_pytorch_conformer
  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/19hrIFuse28HmToR1HiXwxPCgLfUahxB4/view?usp=sharing
    - training config file: `conf/train_conformer_standard.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_cy/cmvn.ark`
    - e2e file: `exp/train_cy_pytorch_conformer/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_cy_pytorch_conformer/results/model.json`
    - lm file: `exp/train_cy_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_cy_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/cy_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cy_decode_lm|2933|91050|90.7|6.0|3.3|1.5|10.8|71.1|
|decode_test_cy_decode_lm|2937|80473|92.9|4.7|2.4|1.2|8.3|38.6|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cy_decode_lm|2933|28498|81.7|16.3|2.0|1.7|20.0|71.1|
|decode_test_cy_decode_lm|2937|26046|87.1|11.5|1.4|1.2|14.2|38.5|


## train_ru_pytorch_conformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1RqZTNi9ovZ8u-BKMHwtzUI4OnMMOz6Wh/view?usp=sharing
    - training config file: `conf/train_conformer_standard.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_ru/cmvn.ark`
    - e2e file: `exp/train_ru_pytorch_conformer/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_ru_pytorch_conformer/results/model.json`
    - lm file: `exp/train_ru_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_ru_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/ru_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_ru_decode_lm|7242|362868|97.9|1.3|0.8|0.3|2.4|33.5|
|decode_test_ru_decode_lm|7307|370347|97.4|1.6|1.0|0.5|3.1|38.3|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_ru_decode_lm|7242|70009|93.5|5.6|0.9|0.4|6.9|33.5|
|decode_test_ru_decode_lm|7307|71189|92.2|6.7|1.1|0.7|8.5|38.3|

## train_it_pytorch_conformer

- Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1XMxoHsyddPqHcfqGrEB5NFTKsS3HdGdj/view?usp=sharing
    - training config file: `conf/train_conformer_standard.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_it/cmvn.ark`
    - e2e file: `exp/train_it_pytorch_conformer/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_it_pytorch_conformer/results/model.json`
    - lm file: `exp/train_it_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_it_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/it_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_it_decode_lm|11904|432724|93.7|3.7|2.6|1.1|7.4|63.5|
|decode_test_it_decode_lm|11900|438847|93.0|4.2|2.8|1.2|8.3|66.7|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_it_decode_lm|11904|116060|85.7|12.7|1.6|1.3|15.6|63.5|
|decode_test_it_decode_lm|11900|117102|84.5|13.8|1.7|1.4|17.0|66.6|

## train_fa_pytorch_conformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1SCCT4ZJw_oLdkAQhy0cBUqLz3qFrN3m3/view?usp=sharing
    - training config file: `conf/train_conformer_standard.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_fa/cmvn.ark`
    - e2e file: `exp/train_fa_pytorch_conformer/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_fa_pytorch_conformer/results/model.json`
    - lm file: `exp/train_fa_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_fa_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/fa_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fa_decode_lm|3989|85268|99.2|0.4|0.4|0.1|0.9|4.6|
|decode_test_fa_decode_lm|3989|88442|98.7|0.8|0.5|0.3|1.6|5.4|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fa_decode_lm|3989|29217|98.7|1.0|0.2|0.2|1.4|4.6|
|decode_test_fa_decode_lm|3989|30347|98.1|1.4|0.5|0.2|2.1|5.4|


## train_cs_pytorch_conformer-small
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|62520|95.0|3.3|1.7|0.4|5.4|35.5|
|decode_test_cs_decode_lm|2574|65285|93.1|4.9|1.9|0.8|7.7|42.7|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|16239|88.7|9.7|1.6|0.7|12.0|35.4|
|decode_test_cs_decode_lm|2574|16508|84.4|13.6|1.9|1.4|16.9|42.7|

## train_cs_pytorch_conformer-med
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|62520|96.6|2.2|1.2|0.3|3.8|25.9|
|decode_test_cs_decode_lm|2574|65285|94.3|4.1|1.6|0.6|6.4|34.1|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|16239|92.0|6.9|1.1|0.5|8.5|25.8|
|decode_test_cs_decode_lm|2574|16508|87.3|11.1|1.6|1.2|13.9|34.1|

## train_cs_pytorch_conformer-large

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1c2m6WMcHq9xToaF57twlvQGp6ydhJuTt/view?usp=sharing
    - training config file: `conf/train_conformer_large.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_cs/cmvn.ark`
    - e2e file: `exp/train_cs_pytorch_conformer-large/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_cs_pytorch_conformer-large/results/model.json`
    - lm file: `exp/train_cs_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_cs_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/cs_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|62520|96.9|2.0|1.0|0.3|3.3|21.1|
|decode_test_cs_decode_lm|2574|65285|94.4|4.0|1.6|0.6|6.2|31.0|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|16239|93.0|6.0|0.9|0.4|7.4|21.1|
|decode_test_cs_decode_lm|2574|16508|87.6|10.9|1.5|1.2|13.6|31.0|


## train_pl_pytorch_conformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1nEd94h1Iy3zG2k1TjhCCL51F75xc5-uE/view?usp=sharing
    - training config file: `conf/train_conformer_standard.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_pl/cmvn.ark`
    - e2e file: `exp/train_pl_pytorch_conformer/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_pl_pytorch_conformer/results/model.json`
    - lm file: `exp/train_pl_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_pl_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/pl_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pl_decode_lm|4458|127033|96.5|1.7|1.8|0.2|3.7|28.5|
|decode_test_pl_decode_lm|4458|118825|98.8|0.6|0.5|0.2|1.3|8.6|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pl_decode_lm|4458|32280|91.6|7.7|0.6|0.5|8.8|28.5|
|decode_test_pl_decode_lm|4458|31588|97.6|2.1|0.3|0.2|2.6|8.6|

## train_kab_pytorch_conformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1UsYCHrRBjlXM1sBoBo6sC4lGmWXQs2V-/view?usp=sharing
    - training config file: `conf/train_conformer_standard.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_kab/cmvn.ark`
    - e2e file: `exp/train_kab_pytorch_conformer/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_kab_pytorch_conformer/results/model.json`
    - lm file: `exp/train_kab_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_kab_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/kab_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_kab_decode_lm|13384|221749|97.9|1.3|0.9|0.4|2.6|18.3|
|decode_test_kab_decode_lm|13384|235672|97.7|1.4|0.9|0.5|2.8|18.9|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_kab_decode_lm|13384|56739|94.6|4.9|0.5|0.3|5.6|18.3|
|decode_test_kab_decode_lm|13384|61644|94.6|4.8|0.6|0.3|5.7|18.9|


## train_nl_pytorch_conformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1H3WMoNC9JRkuynZ1O5tc5b_LkQvLw1ay/view?usp=sharing
    - training config file: `conf/train_conformer_standard.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_nl/cmvn.ark`
    - e2e file: `exp/train_nl_pytorch_conformer/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_nl_pytorch_conformer/results/model.json`
    - lm file: `exp/train_nl_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_nl_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/nl_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_nl_decode_lm|2198|57225|97.3|1.8|1.0|0.4|3.1|10.6|
|decode_test_nl_decode_lm|2198|55930|99.2|0.5|0.3|0.1|0.9|4.7|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_nl_decode_lm|2198|18481|95.9|3.6|0.5|0.6|4.8|10.6|
|decode_test_nl_decode_lm|2198|18259|98.8|1.0|0.2|0.1|1.4|4.7|

## train_fr_pytorch_conformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1fLbQlo0P8_iC5z_o9VmpwBBe5nxm5czf/view?usp=sharing
    - training config file: `conf/train_conformer_standard.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_fr/cmvn.ark`
    - e2e file: `exp/train_fr_pytorch_conformer/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_fr_pytorch_conformer/results/model.json`
    - lm file: `exp/train_fr_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_fr_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/fr_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fr_decode_lm|15621|565882|94.9|3.5|1.7|1.0|6.2|54.3|
|decode_test_fr_decode_lm|15621|573809|93.9|4.1|2.0|1.2|7.3|58.8|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fr_decode_lm|15621|148984|87.9|11.2|0.9|0.8|12.9|54.3|
|decode_test_fr_decode_lm|15621|151227|86.3|12.7|1.0|1.1|14.8|58.8|

## train_es_pytorch_conformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1rUgqXAPBmzkswOhyPd-VuJou5BIHfNgM/view?usp=sharing
    - training config file: `conf/train_conformer_standard.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_es/cmvn.ark`
    - e2e file: `exp/train_es_pytorch_conformer/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_es_pytorch_conformer/results/model.json`
    - lm file: `exp/train_es_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_es_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/es_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_es_decode_lm|14860|512773|94.9|2.8|2.3|1.0|6.1|51.6|
|decode_test_es_decode_lm|14860|513484|94.5|3.1|2.4|1.1|6.7|53.9|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_es_decode_lm|14860|146643|89.9|9.2|0.9|0.8|11.0|51.5|
|decode_test_es_decode_lm|14860|146742|89.2|9.8|1.0|1.0|11.8|53.9|

## train_cy_pytorch_train_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cy_decode_lm|2933|91050|85.2|9.4|5.4|2.1|17.0|88.4|
|decode_test_cy_decode_lm|2937|80473|88.9|7.0|4.0|1.6|12.7|49.4|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cy_decode_lm|2933|28498|70.8|25.5|3.7|2.8|32.0|88.3|
|decode_test_cy_decode_lm|2937|26046|80.3|17.3|2.4|2.1|21.8|49.4|

## train_tt_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1k7mpjiHacFP0exKzznMlkqbqoFtZLwnD/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_tt/cmvn.ark`
    - e2e file: `exp/train_tt_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_tt_pytorch_train/results/model.json`
    - lm file: `exp/train_tt_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_tt_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/tt_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_tt_decode_lm|2116|56115|68.8|21.0|10.2|4.3|35.6|96.2|
|decode_test_tt_decode_lm|4365|114507|67.6|22.6|9.8|5.9|38.3|96.0|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_tt_decode_lm|2116|11916|33.6|59.6|6.8|4.8|71.2|96.1|
|decode_test_tt_decode_lm|4365|24331|32.5|61.1|6.4|5.8|73.3|96.0|

## train_ru_pytorch_train_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_ru_decode_lm|7242|361341|93.0|4.6|2.4|1.2|8.2|72.9|
|decode_test_ru_decode_lm|7307|369397|90.9|6.3|2.9|1.8|10.9|78.6|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_ru_decode_lm|7242|70009|79.6|17.9|2.4|1.6|22.0|72.9|
|decode_test_ru_decode_lm|7307|71189|74.9|22.2|2.9|2.2|27.3|78.6|

## train_fr_pytorch_train_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fr_decode_lm|15621|564488|91.0|6.2|2.8|1.6|10.7|69.7|
|decode_test_fr_decode_lm|15621|572573|89.1|7.6|3.3|2.0|12.9|74.6|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fr_decode_lm|15621|148984|81.2|17.1|1.7|1.6|20.4|69.6|
|decode_test_fr_decode_lm|15621|151227|78.4|19.6|2.0|2.0|23.6|74.6|

## train_eu_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1nuHHroL_YbqYjBQa_v6PLZgBiEmdBDMo/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_eu/cmvn.ark`
    - e2e file: `exp/train_eu_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_eu_pytorch_train/results/model.json`
    - lm file: `exp/train_eu_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_eu_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/eu_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_eu_decode_lm|4912|150513|94.6|3.6|1.8|0.8|6.3|52.9|
|decode_test_eu_decode_lm|4912|150025|94.2|3.8|1.9|1.0|6.8|54.0|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_eu_decode_lm|4912|36451|86.4|12.4|1.2|1.1|14.7|52.7|
|decode_test_eu_decode_lm|4912|36317|85.6|13.2|1.2|1.2|15.6|54.0|

## train_kab_pytorch_train_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_kab_decode_lm|13384|221488|93.1|4.6|2.3|1.1|8.1|41.6|
|decode_test_kab_decode_lm|13384|235597|92.5|5.0|2.5|1.3|8.8|43.5|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_kab_decode_lm|13384|56739|84.7|13.8|1.6|1.0|16.3|41.6|
|decode_test_kab_decode_lm|13384|61644|84.2|14.1|1.7|1.1|16.9|43.5|

## train_fa_pytorch_train_transformer

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fa_decode_lm|3989|85354|95.6|2.2|2.2|0.3|4.7|30.8|
|decode_test_fa_decode_lm|3989|88532|94.6|2.8|2.6|0.5|5.9|35.2|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fa_decode_lm|3989|29217|92.1|6.5|1.5|0.5|8.5|30.8|
|decode_test_fa_decode_lm|3989|30347|90.5|7.6|1.9|0.7|10.2|35.2|

## train_es_pytorch_train_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_es_decode_lm|14860|518025|88.7|7.0|4.3|2.3|13.6|79.0|
|decode_test_es_decode_lm|14860|518844|87.7|7.9|4.5|2.6|15.0|80.7|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_test_es_decode_lm|14860|146742|75.4|21.1|3.4|2.0|26.6|80.6|

## train_zh_TW_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1aDEhNAvyaQrFRcR1L-Uq3wumDjjqH7G4/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_zh_TW/cmvn.ark`
    - e2e file: `exp/train_zh_TW_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_zh_TW_pytorch_train/results/model.json`
    - lm file: `exp/train_zh-TW_rnnlm_pytorch_lm_unigram2500/rnnlm.model.best`
    - lm JSON file: `exp/train_zh-TW_rnnlm_pytorch_lm_unigram2500/model.json`
    - dict file: `data/zh-TW_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_zh_TW_decode_lm|2627|23553|97.8|1.8|0.4|0.2|2.5|8.9|
|decode_test_zh_TW_decode_lm|2627|23304|96.5|2.6|0.9|0.4|3.9|11.5|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_zh_TW_decode_lm|2627|2627|91.1|8.9|0.0|0.0|8.9|8.9|
|decode_test_zh_TW_decode_lm|2627|2627|88.5|11.5|0.0|0.0|11.5|11.5|

## train_de_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1m6Se64Mg5JTf5C5Bsh8y0IYwxIaHaaHd/view?usp=sharing
    - training config file: `conf/tuning/train_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_de/cmvn.ark`
    - e2e file: `exp/train_de_pytorch_train_transformer_specaug/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_de_pytorch_train_transformer_specaug/results/model.json`
    - lm file: `exp/train_de_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_de_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/de_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_de_decode_lm|15341|560719|95.2|3.0|1.8|0.8|5.6|49.3|
|decode_test_de_decode_lm|15341|544386|95.1|3.2|1.8|0.8|5.7|44.8|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_de_decode_lm|15341|140213|89.9|9.1|0.9|1.1|11.1|49.1|
|decode_test_de_decode_lm|15341|137514|90.2|8.9|1.0|1.0|10.8|44.7|

## train_ca_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1NWv7XVWpLLFI5gYmTV509n_aNVk_7il0/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_ca/cmvn.ark`
    - e2e file: `exp/train_ca_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_ca_pytorch_train/results/model.json`
    - lm file: `exp/train_ca_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_ca_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/ca_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_ca_decode_lm|15364|556398|94.4|3.8|1.9|1.1|6.7|58.3|
|decode_test_ca_decode_lm|15364|550769|94.0|4.1|1.9|1.3|7.3|58.9|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_ca_decode_lm|15364|157186|87.1|11.0|1.9|0.9|13.7|58.2|
|decode_test_ca_decode_lm|15364|155763|86.4|11.6|2.0|1.0|14.6|58.9|

## train_it_pytorch_train_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_it_decode_lm|11904|431616|86.4|8.9|4.7|2.3|15.9|86.0|
|decode_test_it_decode_lm|11900|437359|85.3|9.7|5.0|2.5|17.2|87.7|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_it_decode_lm|11904|116060|71.0|25.5|3.5|2.9|31.8|85.9|
|decode_test_it_decode_lm|11900|117102|69.5|26.8|3.8|3.2|33.7|87.6|

## train_tr_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1KODnDC1A-ezBTE9P44O_5vMHQaw5FerP/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_tr/cmvn.ark`
    - e2e file: `exp/train_tr_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_tr_pytorch_train/results/model.json`
    - lm file: `exp/train_tr_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_tr_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/tr_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_tr_decode_lm|1638|43038|85.1|9.5|5.4|2.6|17.4|75.6|
|decode_test_tr_decode_lm|1639|42691|83.1|10.9|6.0|3.3|20.2|76.0|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_tr_decode_lm|1638|9616|67.8|29.0|3.3|2.7|34.9|75.5|
|decode_test_tr_decode_lm|1639|9646|65.7|30.7|3.6|3.1|37.4|75.9|

## train_nl_pytorch_train_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_nl_decode_lm|2198|57507|89.7|7.1|3.2|1.6|12.0|59.3|
|decode_test_nl_decode_lm|2198|56191|90.0|7.1|2.9|1.7|11.7|55.3|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_nl_decode_lm|2198|18481|83.5|14.4|2.1|2.2|18.7|59.3|
|decode_test_nl_decode_lm|2198|18259|84.1|13.7|2.2|1.9|17.8|55.3|

## train_eo_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1d8IfV4SgXffCBW6xuLwmwFdEqaz8xIeo/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_eo/cmvn.ark`
    - e2e file: `exp/train_eo_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_eo_pytorch_train/results/model.json`
    - lm file: `exp/train_eo_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_eo_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/eo_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_eo_decode_lm|8437|227705|88.8|7.2|4.0|1.9|13.1|76.7|
|decode_test_eo_decode_lm|8453|231568|83.9|11.0|5.2|3.0|19.1|83.9|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_eo_decode_lm|8437|65440|75.6|22.3|2.2|1.8|26.3|76.6|
|decode_test_eo_decode_lm|8453|65874|67.4|29.3|3.3|2.5|35.1|83.8|

## train_zh_CN_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1XNdzHctQhadloZ7annhw_57M_pTH1N-d/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_zh_CN/cmvn.ark`
    - e2e file: `exp/train_zh_CN_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_zh_CN_pytorch_train/results/model.json`
    - lm file: `exp/train_zh-CN_rnnlm_pytorch_lm_unigram4500/rnnlm.model.best`
    - lm JSON file: `exp/train_zh-CN_rnnlm_pytorch_lm_unigram4500/model.json`
    - dict file: `data/zh-CN_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_zh_CN_decode_lm|8249|125267|65.0|30.4|4.5|3.0|37.9|92.4|
|decode_test_zh_CN_decode_lm|8273|121367|63.8|31.9|4.3|3.6|39.8|93.6|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_zh_CN_decode_lm|8249|8249|7.9|92.1|0.0|0.0|92.1|92.1|
|decode_test_zh_CN_decode_lm|8273|8273|6.6|93.4|0.0|0.0|93.4|93.4|

## train_pt_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1WGuFNFtb_K3M24nJgYhR0fVdS5Qy8ib0/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_pt/cmvn.ark`
    - e2e file: `exp/train_pt_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_pt_pytorch_train/results/model.json`
    - lm file: `exp/train_pt_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_pt_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/pt_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pt_decode_lm|4329|109562|83.4|10.9|5.7|2.7|19.3|77.2|
|decode_test_pt_decode_lm|4334|112169|80.7|12.7|6.5|3.4|22.7|80.4|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pt_decode_lm|4329|33082|71.2|24.3|4.4|2.8|31.6|77.2|
|decode_test_pt_decode_lm|4334|33716|67.5|27.2|5.3|3.1|35.5|80.4|

## train_rw_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1Cn-f4HePi37hUHHhGEso17Ly6cV9SqwW/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_rw/cmvn.ark`
    - e2e file: `exp/train_rw_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_rw_pytorch_train/results/model.json`
    - lm file: `exp/train_rw_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_rw_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/rw_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_rw_decode_lm|14124|489321|84.6|10.0|5.3|2.5|17.9|84.5|
|decode_test_rw_decode_lm|14251|451153|80.9|12.8|6.3|3.5|22.6|86.9|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_rw_decode_lm|14124|128619|69.2|26.6|4.2|2.7|33.5|84.5|
|decode_test_rw_decode_lm|14251|117926|63.5|31.6|4.9|3.5|40.0|86.9|

## train_uk_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1DJq8ZSnvApgXPgrAtQpk-hT51MqNGVB9/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_uk/cmvn.ark`
    - e2e file: `exp/train_uk_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_uk_pytorch_train/results/model.json`
    - lm file: `exp/train_uk_rnnlm_pytorch_lm_unigram150/rnnlm.model.best`
    - lm JSON file: `exp/train_uk_rnnlm_pytorch_lm_unigram150/model.json`
    - dict file: `data/uk_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_uk_decode_lm|1669|58581|78.6|14.9|6.5|3.5|24.9|92.3|
|decode_test_uk_decode_lm|1671|57866|74.4|18.0|7.7|4.0|29.6|93.9|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_uk_decode_lm|1669|12492|47.1|46.5|6.3|4.4|57.3|92.3|
|decode_test_uk_decode_lm|1671|12291|41.9|51.0|7.1|4.6|62.7|93.9|

## train_cs_pytorch_train_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|62452|83.8|11.5|4.7|1.7|17.9|78.3|
|decode_test_cs_decode_lm|2574|65232|81.1|14.0|4.9|2.4|21.4|81.9|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|16239|64.4|30.3|5.3|2.6|38.2|78.3|
|decode_test_cs_decode_lm|2574|16508|59.2|35.3|5.6|3.5|44.3|81.9|

## train_zh_HK_pytorch_train_transformer

  - Model files (archived to model.tar.gz by `$ pack_model.sh`)
    - model link: https://drive.google.com/file/d/1PcArQDzNJVD7IMiFfgGGU1EvLJWCpBJu/view?usp=sharing
    - training config file: `conf/tuning/train_pytorch_transformer.yaml`
    - decoding config file: `conf/decode.yaml`
    - cmvn file: `data/train_zh_HK/cmvn.ark`
    - e2e file: `exp/train_zh_HK_pytorch_train/results/model.last10.avg.best`
    - e2e JSON file: `exp/train_zh_HK_pytorch_train/results/model.json`
    - lm file: `exp/train_zh-HK_rnnlm_pytorch_lm_unigram4500/rnnlm.model.best`
    - lm JSON file: `exp/train_zh-HK_rnnlm_pytorch_lm_unigram4500/model.json`
    - dict file: `data/zh-HK_lang_char/`


### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_zh_HK_decode_lm|2805|21650|84.6|9.6|5.8|1.1|16.5|30.4|
|decode_test_zh_HK_decode_lm|2805|21123|83.9|10.4|5.7|1.5|17.5|30.3|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_zh_HK_decode_lm|2805|2819|69.8|30.0|0.1|0.0|30.2|30.2|
|decode_test_zh_HK_decode_lm|2805|2815|69.8|30.1|0.1|0.1|30.3|30.3|

## train_pl_pytorch_train_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pl_decode_lm|4458|126403|90.0|5.9|4.1|1.1|11.1|61.5|
|decode_test_pl_decode_lm|4458|118405|93.4|4.3|2.3|1.0|7.6|45.2|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pl_decode_lm|4458|32280|77.6|20.0|2.4|1.8|24.1|61.5|
|decode_test_pl_decode_lm|4458|31588|86.1|12.0|1.9|1.2|15.1|45.2|

## train_cy_pytorch_train_transformer_specaug
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cy_decode_lm|2933|91050|88.2|7.3|4.5|1.6|13.4|75.6|
|decode_test_cy_decode_lm|2937|80473|91.4|5.5|3.1|1.3|9.9|40.0|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cy_decode_lm|2933|28498|78.1|19.1|2.7|1.9|23.7|75.5|
|decode_test_cy_decode_lm|2937|26046|85.2|13.1|1.8|1.3|16.1|40.0|

## train_cs_pytorch_train_transformer_specaug
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|62452|93.6|4.3|2.1|0.6|7.1|42.7|
|decode_test_cs_decode_lm|2574|65232|91.4|6.2|2.5|1.2|9.9|50.1|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_lm|2584|16239|85.8|12.1|2.1|1.1|15.3|42.6|
|decode_test_cs_decode_lm|2574|16508|81.3|16.4|2.4|1.8|20.6|50.1|

## train_cs_pytorch_rnn
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_rnn_lm|2584|62452|85.4|10.3|4.3|1.5|16.2|70.7|
|decode_test_cs_decode_rnn_lm|2574|65232|82.6|13.2|4.2|2.4|19.8|74.5|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_rnn_lm|2584|16239|68.6|26.3|5.1|2.0|33.5|70.7|
|decode_test_cs_decode_rnn_lm|2574|16508|63.9|31.2|4.9|3.5|39.6|74.5|

## train_ru_pytorch_rnn
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_ru_decode_rnn_lm|7242|361341|91.4|5.8|2.9|1.5|10.1|78.5|
|decode_test_ru_decode_rnn_lm|7307|369397|89.0|7.7|3.3|2.2|13.2|82.7|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_ru_decode_rnn_lm|7242|70009|75.8|21.2|3.0|2.0|26.2|78.4|
|decode_test_ru_decode_rnn_lm|7307|71189|70.9|25.8|3.3|2.7|31.8|82.7|

## train_cy_pytorch_rnn
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cy_decode_rnn_lm|2933|91050|83.2|10.6|6.2|2.3|19.1|90.2|
|decode_test_cy_decode_rnn_lm|2937|80473|87.7|7.8|4.5|1.8|14.1|51.9|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cy_decode_rnn_lm|2933|28498|68.3|27.7|4.0|3.0|34.8|90.2|
|decode_test_cy_decode_rnn_lm|2937|26046|78.6|18.6|2.8|1.9|23.3|51.9|

## train_it_pytorch_rnn
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_it_decode_rnn_lm|11904|431616|85.7|9.5|4.8|2.4|16.7|85.8|
|decode_test_it_decode_rnn_lm|11900|437359|84.7|10.3|5.0|2.6|18.0|87.6|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_it_decode_rnn_lm|11904|116060|70.5|26.0|3.6|2.9|32.5|85.8|
|decode_test_it_decode_rnn_lm|11900|117102|68.9|27.4|3.7|3.2|34.4|87.6|


## train_fa_pytorch_rnn
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fa_decode_rnn_lm|3989|85354|93.5|3.3|3.2|0.4|6.9|40.5|
|decode_test_fa_decode_rnn_lm|3989|88532|92.5|3.8|3.7|0.6|8.1|45.0|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_fa_decode_rnn_lm|3989|29217|88.1|9.6|2.2|0.9|12.8|40.5|
|decode_test_fa_decode_rnn_lm|3989|30347|86.7|10.5|2.8|1.1|14.4|45.0|


## train_kab_pytorch_rnn
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_kab_decode_rnn_lm|13384|221488|90.5|6.3|3.2|1.5|11.0|52.3|
|decode_test_kab_decode_rnn_lm|13384|235597|89.9|6.6|3.5|1.7|11.8|55.5|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_kab_decode_rnn_lm|13384|56739|78.9|19.0|2.1|1.3|22.4|52.3|
|decode_test_kab_decode_rnn_lm|13384|61644|78.0|19.5|2.6|1.4|23.5|55.5|

## train_pl_pytorch_rnn
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pl_decode_rnn_lm|4458|126403|88.8|6.6|4.6|1.2|12.4|66.2|
|decode_test_pl_decode_rnn_lm|4458|118405|92.3|4.8|2.9|1.0|8.7|48.1|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pl_decode_rnn_lm|4458|32280|75.0|22.0|3.0|2.1|27.0|66.2|
|decode_test_pl_decode_rnn_lm|4458|31588|84.3|13.0|2.6|1.4|17.1|48.0|

## train_pl_pytorch_sp_transformer
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pl_decode_lm|4458|127033|96.4|1.7|1.9|0.3|3.8|28.1|
|decode_test_pl_decode_lm|4458|118825|98.8|0.6|0.5|0.2|1.3|8.2|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_pl_decode_lm|4458|32280|91.6|7.8|0.6|0.5|8.9|28.1|
|decode_test_pl_decode_lm|4458|31588|97.6|2.1|0.3|0.2|2.6|8.1|

# Transducer

## Summary

|Lang|Model|Algo|CER¹|WER¹|SER¹|RTF¹²|
|-|-|-|-|-|-|-|
|cs³|Conformer/RNN-T|default|7.9|15.3|30.4|0.089|
|-|-|ALSD|8.2|15.6|30.8|0.080|
|-|-|TSD|8.1|15.5|31.3|0.111|
|-|-|NSC|8.0|15.5|30.8|0.123|
|-|-|mAES|8.1|15.5|31.0|0.081|
|-|Conformer/RNN-T + Aux|default|8.0|14.7|27.8|0.200|
|-|-|ALSD|8.4|14.9|27.7|0.080|
|-|-|TSD|7.8|14.6|27.4|0.107|
|-|-|NSC|7.9|14.5|27.4|0.123|
|-|-|mAES|8.0|14.8|27.7|0.082|

¹ Reported on the test set only.
² RTF was computed using `line-profiler` tool applied to [recognize method](https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_asr_transducer.py#L470). The reported value is averaged on 5 runs with `nj=1`. All experiments were performed using a single AMD EPYC 7502P.
³ We do not use a language model for these experiments.

## Czech (cs)

### Conformer/RNN-Transducer (Enc: VGG + 12 x Conformer, Dec: 1 x LSTM)

- General information
  - GPU: Nvidia A100 40Gb
  - Peak VRAM usage during training: ~ 24.3 GiB
  - Training time: ~ 8 hours and 5 minutes
  - Decoding time (4 jobs, `search-type: default`): ~ 3 minutes and 30 seconds
  - Model averaging: `n_average=20`, `use_valbest_average=true`

- Environments
  - date: `Wed Aug 22 08:54:04 UTC 2021`
  - python version: `3.8.5 (default, Sept  4 2020, 07:30:14)  [GCC 7.3.0]`
  - espnet version: `espnet 0.10.2a1`
  - chainer version: `chainer 6.0.0`
  - pytorch version: `pytorch 1.8.1`
  - Git hash: `4406f25ebf507daf33f68787ff0e3699a0937913`
  - Commit date: `Sat Aug 14 06:25:18 2021 -0400`

- Model files
  - model link: https://drive.google.com/file/d/11zF8CCQMWG4rcR4nLe3tdGoyXgJMu3Nf
  - training config file: `conf/tuning/transducer/cs/train_conformer-rnn_transducer.yaml`
  - decoding config file: `conf/tuning/transducer/cs/decode_default.yaml`
  - cmvn file: `data/train_cs/cmvn.ark`
  - e2e file: `exp/train_cs_pytorch_cs_train_conformer-rnn_transducer_specaug/results/model.val20.avg.best`
  - e2e JSON file: `exp/train_cs_pytorch_cs_train_conformer-rnn_transducer_specaug/results/model.json`
  - dict file: `data/cs_lang_char/`

### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_alsd|2584|62520|96.2|2.6|1.2|0.5|4.3|20.7|
|decode_dev_cs_decode_default|2584|62520|96.3|2.6|1.1|0.5|4.2|20.4|
|decode_dev_cs_decode_maes|2584|62520|96.0|2.7|1.2|0.5|4.5|21.1|
|decode_dev_cs_decode_nsc|2584|62520|96.0|2.7|1.3|0.5|4.5|21.1|
|decode_dev_cs_decode_tsd|2584|62520|95.8|2.8|1.4|0.5|4.6|21.9|
|decode_test_cs_decode_alsd|2574|65285|92.9|5.2|1.9|1.1|8.2|30.8|
|decode_test_cs_decode_default|2574|65285|93.1|5.0|1.8|1.0|7.9|30.4|
|decode_test_cs_decode_maes|2574|65285|92.9|5.1|2.0|1.0|8.1|31.0|
|decode_test_cs_decode_nsc|2574|65285|93.0|5.1|2.0|1.0|8.0|30.8|
|decode_test_cs_decode_tsd|2574|65285|92.8|5.1|2.0|1.0|8.1|31.3|

### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_alsd|2584|16239|92.3|6.5|1.2|0.7|8.4|20.7|
|decode_dev_cs_decode_default|2584|16239|92.3|6.5|1.1|0.7|8.4|20.4|
|decode_dev_cs_decode_maes|2584|16239|92.1|6.7|1.3|0.8|8.7|21.1|
|decode_dev_cs_decode_nsc|2584|16239|92.1|6.7|1.2|0.7|8.7|21.1|
|decode_dev_cs_decode_tsd|2584|16239|91.8|6.9|1.3|0.7|9.0|21.9|
|decode_test_cs_decode_alsd|2574|16508|86.0|12.2|1.8|1.7|15.6|30.8|
|decode_test_cs_decode_default|2574|16508|86.3|11.9|1.8|1.6|15.3|30.4|
|decode_test_cs_decode_maes|2574|16508|86.0|12.1|1.9|1.5|15.5|31.0|
|decode_test_cs_decode_nsc|2574|16508|86.1|12.0|1.9|1.5|15.5|30.7|
|decode_test_cs_decode_tsd|2574|16508|85.9|12.1|2.0|1.5|15.6|31.2|

### Conformer/RNN-Transducer (Enc: VGG + 12 x Conformer, Dec: 1 x LSTM)
##   + CTC loss + Label Smoothing loss + aux. Transducer loss + symm. KL div loss

- General information
  - GPU: Nvidia A100 40Gb
  - Peak VRAM usage during training: ~ 38.2 GiB
  - Training time: ~ 9 hours and 34 minutes
  - Decoding time (4 jobs, `search-type: default`): ~ 6 minutes and 28 seconds
  - Model averaging: `n_average=20`, `use_valbest_average=true`

- Environments
  - date: `Wed Aug 22 08:54:04 UTC 2021`
  - python version: `3.8.5 (default, Sept  4 2020, 07:30:14)  [GCC 7.3.0]`
  - espnet version: `espnet 0.10.2a1`
  - chainer version: `chainer 6.0.0`
  - pytorch version: `pytorch 1.8.1`
  - Git hash: `4406f25ebf507daf33f68787ff0e3699a0937913`
  - Commit date: `Sat Aug 14 06:25:18 2021 -0400`

- Model files
  - model link: https://drive.google.com/file/d/1Ik8EpLeedsGYTIPNJXjZkUqcElEBv1gV
  - training config file: `conf/tuning/transducer/cs/train_conformer-rnn_transducer_aux.yaml`
  - decoding config file: `conf/tuning/transducer/cs/decode_default.yaml`
  - cmvn file: `data/train_cs/cmvn.ark`
  - e2e file: `exp/train_cs_pytorch_cs_train_conformer-rnn_transducer_aux_specaug/results/model.val20.avg.best`
  - e2e JSON file: `exp/train_cs_pytorch_cs_train_conformer-rnn_transducer_aux_specaug/results/model.json`
  - dict file: `data/cs_lang_char/`

#### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_alsd|2584|62520|96.3|1.8|1.8|0.4|4.1|16.5|
|decode_dev_cs_decode_default|2584|62520|96.5|1.8|1.7|0.4|3.9|17.0|
|decode_dev_cs_decode_maes|2584|62520|96.4|1.8|1.8|0.4|3.9|16.8|
|decode_dev_cs_decode_nsc|2584|62520|96.5|1.8|1.7|0.4|3.8|16.6|
|decode_dev_cs_decode_tsd|2584|62520|96.5|1.8|1.7|0.3|3.8|17.0|
|decode_test_cs_decode_alsd|2574|65285|92.6|4.1|3.2|1.0|8.4|27.7|
|decode_test_cs_decode_default|2574|65285|92.9|4.0|3.0|0.9|8.0|27.8|
|decode_test_cs_decode_maes|2574|65285|92.8|4.1|3.1|0.9|8.0|27.7|
|decode_test_cs_decode_nsc|2574|65285|92.9|4.0|3.0|0.8|7.9|27.4|
|decode_test_cs_decode_tsd|2574|65285|92.9|4.0|3.1|0.8|7.8|27.4|

#### WER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_dev_cs_decode_alsd|2584|16239|93.0|5.3|1.7|0.5|7.4|16.5|
|decode_dev_cs_decode_default|2584|16239|93.1|5.4|1.5|0.6|7.5|17.0|
|decode_dev_cs_decode_maes|2584|16239|93.1|5.2|1.6|0.5|7.3|16.8|
|decode_dev_cs_decode_nsc|2584|16239|93.2|5.2|1.6|0.5|7.2|16.6|
|decode_dev_cs_decode_tsd|2584|16239|93.2|5.3|1.6|0.5|7.3|17.0|
|decode_test_cs_decode_alsd|2574|16508|86.2|11.0|2.8|1.0|14.9|27.7|
|decode_test_cs_decode_default|2574|16508|86.3|11.0|2.7|1.0|14.7|27.8|
|decode_test_cs_decode_maes|2574|16508|86.2|11.1|2.7|1.0|14.8|27.7|
|decode_test_cs_decode_nsc|2574|16508|86.4|10.9|2.7|0.9|14.5|27.4|
|decode_test_cs_decode_tsd|2574|16508|86.3|10.9|2.8|0.9|14.6|27.4|
