#!/usr/bin/env bash

# NOTE: DO NOT WRITE DISTRIBUTION-SPECIFIC COMMANDS HERE (e.g., apt, dnf, etc)

set -euo pipefail

# Timer functions for measuring command execution time
start_timer() {
    local label="$1"
    echo "::group::$label"
    SECONDS=0
}

end_timer() {
    local label="$1"
    echo "::endgroup::"
    local elapsed=$SECONDS
    printf "⏱️  %s completed in %02d:%02d:%02d\n" "$label" $((elapsed/3600)) $((elapsed%3600/60)) $((elapsed%60))
}

${CXX:-g++} -v

(
    set -euo pipefail
    cd tools

    # To skip error
    mkdir -p kaldi/egs/wsj/s5/utils && touch kaldi/egs/wsj/s5/utils/parse_options.sh
    if ${USE_CONDA}; then
        ./setup_miniforge.sh venv espnet ${ESPNET_PYTHON_VERSION}
        # To install via pip instead of conda
    else
        ./setup_venv.sh "$(command -v python3)" venv
    fi

    . ./activate_python.sh
    # FIXME(kamo): Failed to compile pesq
    # TODO(nelson): Reorder versa and s3prl. Currently, versa is using a forked S3PRL that breaks CI, due to PyTorch versions.
    make TH_VERSION="${TH_VERSION}" WITH_OMP="${WITH_OMP-ON}" all \
        warp-transducer.done versa.done nkf.done moses.done \
        pyopenjtalk.done py3mmseg.done transformers.done \
        phonemizer.done fairseq.done k2.done longformer.done \
        parallel-wavegan.done muskits.done lora.done sph2pipe \
        torcheval.done whisper.done s3prl.done
    rm -rf kaldi
)
. tools/activate_python.sh
python3 --version

start_timer "install kenlm"
# kenlm's setup.py compiles the python/kenlm.cpp checked into its repository,
# and that file was generated by a Cython old enough to call CPython private
# APIs which 3.13 removed. On python 3.13 the build dies with:
#
#   error: '_PyDict_SetItem_KnownHash' was not declared in this scope
#   error: too few arguments to function 'int _PyLong_AsByteArray(...)'
#   error: '_PyGen_SetStopIterationValue' was not declared in this scope
#
# The guard around the first reads `PY_VERSION_HEX >= 0x030500A1`, so 3.13 walks
# into a branch that no longer exists. Cython 3.3 emits the same call under
# `PY_VERSION_HEX < 0x030d0000` instead - verified on all three symbols - so
# regenerating from the python/kenlm.pyx that ships beside it is the whole fix.
#
# There is nothing to upgrade to instead: upstream has had no commit since
# 2025-03-30, and PyPI offers kenlm only as an sdist, which compiles the same
# stale file. Regenerating unconditionally rather than only on 3.13, so every
# python here builds kenlm the same way.
python3 -m pip install "cython>=3.1"
kenlm_src="$(mktemp -d)"
git clone --depth 1 https://github.com/kpu/kenlm.git "${kenlm_src}/kenlm"
python3 -m cython --cplus \
    "${kenlm_src}/kenlm/python/kenlm.pyx" \
    -o "${kenlm_src}/kenlm/python/kenlm.cpp"
python3 -m pip install "${kenlm_src}/kenlm"
rm -rf "${kenlm_src}"
end_timer "install kenlm"
start_timer "warm matplotlib cache"
# NOTE(kamo): Create matplotlib.cache to reduce runtime for test phase
python3 -c "import matplotlib.pyplot"
end_timer "warm matplotlib cache"
# NOTE(wangyou): onnxruntime and onnx2torch are used for testing dnsmos functions
cat >> constraints.txt << EOF
torch==${TH_VERSION}
EOF
start_timer "install onnxruntime onnx2torch"
python3 -m pip install -c constraints.txt onnxruntime onnx2torch --extra-index-url https://download.pytorch.org/whl/cpu
end_timer "install onnxruntime onnx2torch"

# NOTE(kan-bayashi): Fix the error in black installation.
#   See: https://github.com/psf/black/issues/1707
python3 -m pip uninstall -y typing

# NOTE(kamo): Workaround for pip resolve issue (I think this is a bug of pip)
start_timer "install hacking flake8"
python3 -m pip install "hacking>=2.0.0" "flake8>=3.7.8"
end_timer "install hacking flake8"

# install espnet
start_timer "install espnet"
python3 -m pip install -e ".[test,all]"
end_timer "install espnet"

# NOTE: omniio provides the Kaldi ark/scp I/O used by espnet2.utils.kaldi_io_utils.
#   It is not on PyPI, so it cannot be an extra of espnet and is installed here to
#   keep the Kaldi code paths covered by CI.
start_timer "install omniio"
python3 -m pip install "omniio @ git+https://github.com/wavlab-speech/omniio.git"
end_timer "install omniio"

# log
python3 -m pip freeze


# Check pytorch version
python3 <<EOF
import torch
from packaging.version import parse as L
version = '$TH_VERSION'.split(".")
next_version = f"{version[0]}.{version[1]}.{int(version[2]) + 1}"

if L(torch.__version__) < L('$TH_VERSION') or L(torch.__version__) >= L(next_version):
    raise RuntimeError(f"Pytorch=$TH_VERSION is expected, but got pytorch={torch.__version__}. This is a bug in installation scripts")
EOF

# Check numpy version
python3 <<EOF
import numpy
from packaging.version import parse as L

if L(numpy.__version__) < L("2.0.0"):
    raise RuntimeError(f"Numpy>=2.0.0 is expected, but got numpy={numpy.__version__}. This is a bug in installation scripts")
EOF
